In [65]:
import pandas as pd
import numpy as np

In [66]:
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)

In [67]:
df = pd.read_csv('flats.csv')

In [68]:
df.sample(5)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
2369,3 BHK Flat in Sector 5 chowk Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Aashirwad Residency,90 Lac,"₹ 11,250/sq.ft.",Carpet area: 800 (74.32 sq.m.),3 Bedrooms,2 Bathrooms,2 Balconies,Others,"Flat 401, 4th Floor, A 34, Sector 5 chowk Gurg...",4th of 4 Floors,NaN,5 to 10 Year Old,NaN,This is 3 bhk flat with written terrace rights...,"['1 Wardrobe', '1 Fan', '1 Light', '1 Chimney'...","['Security / Fire Alarm', 'Intercom Facility',...",NaN,Y66707356
1890,2 BHK Flat in Sector 113 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,La Vida by Tata Housing,1.35 Crore,"₹ 13,989/sq.ft.",Super Built up area 1276(118.54 sq.m.)Built Up...,2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"On The Bang Of Dwarka Expressway., Sector 113 ...",10th of 13 Floors,North-East,0 to 1 Year Old,"['Dwarka Sector 21', 'Pacific D21 Mall', 'Bajg...",Amazing property with lavish clubhouse.2 bhk f...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Centrally Air Conditioned', 'Water purifier'...",NaN,W68450138
1148,2 BHK Flat in Sector 107 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Signature Global Solera3.7 ★,36 Lac,"₹ 5,980/sq.ft.",Super Built up area 602(55.93 sq.m.)Built Up a...,2 Bedrooms,2 Bathrooms,1 Balcony,Others,"A3-708, Sector 107 Gurgaon, Gurgaon, Haryana",7th of 14 Floors,North-West,1 to 5 Year Old,"['Gurgaon Dreamz Mall', 'Dwarka Expressway', ""...","Situated in sector 107 gurgaon, signature glob...",NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4.5 out of 5', 'Construction4.5 ou...",C69403800
859,3 BHK Flat in Sector 110 A Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Mahindra Aura4.2 ★,1.4 Crore,"₹ 9,655/sq.ft.",Super Built up area 1615(150.04 sq.m.)Built Up...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"110a, Sector 110 A Gurgaon, Gurgaon, Haryana",10th of 14 Floors,North,1 to 5 Year Old,"['Global Foyer Mall, Palam Vihar', 'Dwarka Ex...",Check out this 3 bhk apartment for sale in mah...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Water purifier', 'Security / Fire Alarm', 'F...","['Green Area5 out of 5', 'Construction4 out of...",B69710156
2090,3 BHK Flat in Sector 74 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,M3M Skywalk,2.7 Crore,"₹ 13,379/sq.ft.",Super Built up area 2018(187.48 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,Store Room,"1305, Sector 74 Gurgaon, Gurgaon, Haryana",13rd of 30 Floors,NaN,0 to 1 Year Old,"['Omaxe Gurgaon Mall', 'Omaxe Celebration Mall...",Spacious room\n3 floor mall inside the project...,[],"['Security / Fire Alarm', 'Power Back-up', 'In...",NaN,P69918002

In [69]:
df.shape

(3017, 20)

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3017 entries, 0 to 3016
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3017 non-null   object
 1   link             3017 non-null   object
 2   society          3016 non-null   object
 3   price            3007 non-null   object
 4   area             3004 non-null   object
 5   areaWithType     3008 non-null   object
 6   bedRoom          3008 non-null   object
 7   bathroom         3008 non-null   object
 8   balcony          3008 non-null   object
 9   additionalRoom   1694 non-null   object
 10  address          3002 non-null   object
 11  floorNum         3006 non-null   object
 12  facing           2127 non-null   object
 13  agePossession    3007 non-null   object
 14  nearbyLocations  2913 non-null   object
 15  description      3008 non-null   object
 16  furnishDetails   2203 non-null   object
 17  features         2594 non-null   object
 18  rating           2676 non-null   object
 19  property_id      3008 non-null   object
dtypes: object(20)
memory usage: 471.5+ KB

In [71]:
df.duplicated().sum()

np.int64(0)

In [72]:
df.isnull().sum()

property_name         0
link                  0
society               1
price                10
area                 13
areaWithType          9
bedRoom               9
bathroom              9
balcony               9
additionalRoom     1323
address              15
floorNum             11
facing              890
agePossession        10
nearbyLocations     104
description           9
furnishDetails      814
features            423
rating              341
property_id           9
dtype: int64

In [73]:
df.drop(columns = ['link', 'property_id'], inplace = True)

In [74]:
df.sample(5)

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2284,3 BHK Flat in Sector 95 Gurgaon,ROF Ananda,55 Lac,"₹ 5,500/sq.ft.",Super Built up area 1000(92.9 sq.m.)Carpet are...,3 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"B Tower 14 Floor, Sector 95 Gurgaon, Gurgaon, ...",14th of 14 Floors,East,0 to 1 Year Old,"['Metro', 'Dwarka Expressway', 'Rajeev Chowk',...",Smi furnished flat with all amenities,"['1 Water Purifier', '3 Fan', '1 Fridge', '1 E...","['Intercom Facility', 'Lift(s)', 'Park', 'Fitn...","['Environment4 out of 5', 'Lifestyle4.5 out of..."
2945,3 BHK Flat in Sector 99A Gurgaon,Pareena Coban Residences,1.35 Crore,"₹ 6,761/sq.ft.",Super Built up area 1997(185.53 sq.m.),3 Bedrooms,5 Bathrooms,3 Balconies,"Servant Room,Others","Sector 99A Gurgaon, Gurgaon, Haryana",6th of 20 Floors,NaN,0 to 1 Year Old,"['Gopal Super Market', 'Little Need Super Mark...",Pareena coban in 99a is a apartment,[],"['Intercom Facility', 'Lift(s)', 'Swimming Poo...","['Safety3 out of 5', 'Lifestyle3 out of 5', 'E..."
699,3 BHK Flat in Sector 106 Gurgaon,Paras Dews,1.15 Crore,"₹ 6,052/sq.ft.",Super Built up area 1900(176.52 sq.m.)Built Up...,3 Bedrooms,4 Bathrooms,3 Balconies,"Study Room,Servant Room","Sector 106 Gurgaon, Gurgaon, Haryana",5th of 24 Floors,North-West,1 to 5 Year Old,"['MG Road Metro Station', 'NeoSquare Shopping ...",Paras dews is one of the most popular destinat...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Feng Shui / Vaastu Compliant', 'Security / F...",NaN
772,4 BHK Flat in Sector 82A Gurgaon,DLF The Primus3.9 ★,2.55 Crore,"₹ 11,218/sq.ft.",Super Built up area 2273(211.17 sq.m.)Carpet a...,4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"000, Sector 82A Gurgaon, Gurgaon, Haryana",14th of 32 Floors,South-West,1 to 5 Year Old,"['Sapphire 83', 'NH 48', 'Cambridge Montessori...","Situated in sector 82a gurgaon, dlf the primus...","['7 Fan', '1 Fridge', '1 Exhaust Fan', '5 Geys...","['Security / Fire Alarm', 'Intercom Facility',...","['Green Area5 out of 5', 'Construction4.5 out ..."
1203,2 BHK Flat in Sector 1 Imt Manesar,HSIIDC Sidco Shivalik Apartments3.8 ★,48 Lac,"₹ 3,840/sq.ft.",Super Built up area 1250(116.13 sq.m.)Carpet a...,2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sector 1 Imt Manesar, Gurgaon, Haryana",7th of 8 Floors,South,5 to 10 Year Old,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",This 2 bhk flat is located in hsiidc sidco shi...,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area4 out of 5', 'Construction4 out of..."

In [75]:
df['society'].value_counts()

society
SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Smart World Gems                                     32
Emaar MGF Emerald Floors Premier3.8 ★                32
Smart World Orchard                                  32
DLF The Ultima4.0 ★                                  31
Paras Dews                                           31
DLF Regal Gardens3.9 ★                               30
Shree Vardhman Flora3.8 ★                            29
M3M Woodshire4.0 ★                                   29
La Vida by Tata Housing                              28
Signature Global Solera3.7 ★                         28
Godrej Nature Plus                                   27
Emaar Gurgaon Greens4.1 ★                            25
BPTP Terra3.8 ★                                      25
Experion The Heartsong3.9 ★                          24
Eldeco Accolade3.8 ★                                 24
Vatika Gurgaon 213.7 ★                               24
DLF New Town Heights 13.9 ★                          24
Bestech Park View Residency3.9 ★                     23
M3M Heights                                          22
Tata Primanti4.1 ★                                   22
ATS Triumph3.9 ★                                     22
Emaar Palm Gardens4.1 ★                              22
ROF Ananda                                           21
Sare Crescent Parc3.5 ★                              21
Godrej 1014.0 ★                                      20
Experion Windchants3.8 ★                             20
Sare Homes                                           19
Antriksh Heights3.7 ★                                19
Ambience Creacions                                   18
ATS Tourmaline3.9 ★                                  18
Indiabulls Centrum Park3.7 ★                         18
Mapsko Mount Ville4.1 ★                              18
Supertech Araville                                   18
CHD Avenue 713.6 ★                                   18
Sobha City                                           18
M3M Golfestate4.4 ★                                  17
Conscient Heritage Max4.3 ★                          17
GLS Arawali Homes3.8 ★                               17
Godrej Summit3.7 ★                                   17
Pareena Coban Residences                             17
M3M Skywalk                                          17
Bestech Park View Grand Spa4.3 ★                     16
M3M Merlin3.7 ★                                      16
HCBS Sports Ville3.6 ★                               16
Umang Monsoon Breeze                                 15
Emaar MGF The Palm Drive4.1 ★                        15
Ansal Heights 86                                     15
Godrej Oasis3.9 ★                                    15
Umang Winter Hills3.9 ★                              14
Ramsons Kshitij3.7 ★                                 14
DLF The Primus3.9 ★                                  14
Orchid Petals4.1 ★                                   14
The Close North4.0 ★                                 14
Ireo Skyon4.0 ★                                      14
Vatika The Seven Lamps3.8 ★                          14
Ireo Victory Valley4.1 ★                             14
Indiabulls Enigma                                    14
Corona Optus3.9 ★                                    14
Imperia The Esfera                                   14
MVN Athens3.7 ★                                      14
Ireo The Corridors                                   13
Bestech Park View Ananda4.2 ★                        13
Puri Emerald Bay3.7 ★                                13
Central Park Flower Valley                           13
M3M Soulitude                                        11
DLF The Skycourt4.2 ★                                11
Godrej Aria3.8 ★                                     11
TARC Maceo3.8 ★                                      11
SBTL Caladium                                        11
Breez Global Hill View                               11
Adani M2K Oyster Grande3.9 ★                         11
Alpha Corp GurgaonOne 844.0 ★                        11
Raheja Vedaanta3.6 ★                                 11
Puri Diplomatic Greens4.0 ★                          10
Capital Residences 360                               10
ATS Kocoon                                           10
Ramprastha The Edge Towers3.5 ★                      10
Signature Global Synera3.4 ★                         10
DLF New Town Heights 24.0 ★                          10
Breez Global Heights4.2 ★                            10
Emaar MGF Palm Hills4.0 ★                            10
Zara Aavaas                                          10
Pyramid Urban Homes 2                                10
Godrej Air                                           10
Pivotal Devaan                                       10
Parsvnath Green Ville3.9 ★                            9
Bestech Park View Sanskruti4.2 ★                      9
AIPL The Peaceful Homes3.9 ★                          9
Pareena Mi Casa                                       9
Microtek Greenburg3.8 ★                               9
ILD Greens4.1 ★                                       9
Vatika City4.1 ★                                      9
Tulip Ivory3.5 ★                                      8
GLS Avenue 51                                         8
ss                                                    8
Bestech Altura                                        8
AVL 36 Gurgaon3.7 ★                                   8
Orris Aster Court Premier                             8
The Lions CGHS                                        8
Emaar Digihomes                                       8
M3M Capital                                           8
Birla Navya                                           8
Assotech Blith                                        8
Vatika Lifestyle Homes3.8 ★                           8
M3M Skycity                                           8
Signature Andour Heights3.8 ★                         7
Emaar Imperial Gardens3.8 ★                           7
Signature Global Orchard Avenue3.6 ★                  7
Sare Crescent Parc Royal Greens Phase 1               7
Mapsko Casa Bella3.8 ★                                7
Vipul Lavanya3.9 ★                                    7
Ireo The Grand Arch4.0 ★                              7
Signature Global City                                 7
Sare Green ParC Phase 3                               7
Ansal Housing Highland Park                           7
Orris Carnation Residency3.7 ★                        7
Trisara Our Homes 3                                   7
AIPL Zen Residences                                   7
DLF Regency Park 13.6 ★                               6
HSIIDC Sidco Aravali                                  6
Bestech Park View City4.1 ★                           6
Signature Global Park 4                               6
Suncity Vatsal Valley                                 6
Mapsko Royale Ville3.7 ★                              6
Sidhartha NCR One Phase 14.2 ★                        6
Greenopolis                                           6
Hero Homes                                            6
Signature Global City 63A                             6
Signature The Roselia3.6 ★                            6
Pyramid Urban                                         6
Shapoorji Pallonji Joyville Gurugram                  6
Supertech Hues                                        6
Ashiana Mulberry                                      6
BPTP Astaire Gardens3.7 ★                             6
Pioneer Araya3.8 ★                                    6
Bestech Park View Spa Next4.0 ★                       6
Parsvnath Exotica3.7 ★                                6
M3M Sierra 68                                         6
Kiran Residency                                       6
Ireo Uptown4.1 ★                                      5
Silverglades The Melia                                5
Signature Global Grand IVA3.9 ★                       5
Conscient Elevate                                     5
Godrej Habitat                                        5
Essel Towers                                          5
Vatika Sovereign Park                                 5
ATS Marigold                                          5
Adani Brahma Samsara Vilasa                           5
Signature Global City 37D Ph 2                        5
Krisumi Waterfall Residences                          5
Central Park Flower Valley Aqua Front Towers          5
Ashiana Anmol3.5 ★                                    5
Green Court3.7 ★                                      5
Vatika City Homes3.9 ★                                5
DLF Park Place4.1 ★                                   5
Pareena Laxmi Apartments3.6 ★                         5
Satya The Hermitage3.5 ★                              5
Emaar MGF Emerald Estate3.8 ★                         5
Pioneer Park3.8 ★                                     5
Signature Global City 92                              5
Signature Global the Millennia                        5
DLF Regency Park 24.0 ★                               5
Central Park Resorts4.4 ★                             5
Tulip Monsella                                        5
M3M The Marina4.0 ★                                   5
Signature Global City 81                              5
Apna Enclave                                          5
Unitech Vistas                                        4
Global Hill View                                      4
Railway Officers RPF Society                          4
Corona Gracieux                                       4
ILD Grand                                             4
Sare Petioles                                         4
Raheja Navodaya3.6 ★                                  4
Ramprastha Primera                                    4
Unitech Fresco3.8 ★                                   4
Signature The Serenas                                 4
Godrej Frontier3.7 ★                                  4
Prime Habitat                                         4
Tata Gurgaon Gateway3.8 ★                             4
Ramprastha Skyz                                       4
HSIIDC Sidco Shivalik Apartments3.8 ★                 4
DLF New Town Heights3.7 ★                             4
SS The Coralwood3.4 ★                                 4
Lotus Homz4.0 ★                                       4
DLF The Skycourt                                      4
Orris Aster Court                                     4
Godrej Icon                                           4
Emaar Palm Heights                                    4
Krrish Provence Estate                                4
Spaze Privvy The Address3.9 ★                         3
DLF The Arbour                                        3
Sare Green Parc 2                                     3
DLF Express Greens3.9 ★                               3
Ambience Lagoon3.9 ★                                  3
Unitech Heritage City                                 3
The Roselia 2                                         3
Valley View Estate                                    3
Sare Green Parc                                       3
Vatika Independent Floors3.8 ★                        3
Kendriya Vihar4.1 ★                                   3
Piedmont Taksila heights3.6 ★                         3
DLF The Grove                                         3
Tulip Petals3.6 ★                                     3
Shri Ram Apartments                                   3
Unitech Uniworld Gardens3.8 ★                         3
Tulip White3.5 ★                                      3
Smriti Apartment                                      3
Sapphire Eighty Three                                 3
DLF Royalton Tower                                    3
DLF Carlton Estate4.0 ★                               3
Sukhshanti Apartment                                  3
SS Almeria                                            3
DLF Belvedere Towers3.8 ★                             3
Satya Element One                                     3
AIPL Club Residences                                  3
Vatika Xpressions                                     3
Raheja Revanta                                        3
My Home                                               3
Brisk Lumbini Terrace Homes                           3
Deepak Minda                                          3
Maxworth City Residences                              3
Apex Our Homes                                        3
Shri Banke Bihari Society3.8 ★                        3
AFNHB Jalvayu Vihar3.7 ★                              3
Spaze Privy AT43.9 ★                                  3
ATS Kocoon4.2 ★                                       3
Dhoot Time Residency4.0 ★                             3
Sidhartha NCR One                                     3
Raheja Sampada                                        3
Sunischit Apartments                                  3
Bestech Park View City 23.9 ★                         3
Pyramid Elite                                         3
Suncity Platinum Towers                               3
Mahindra Aura4.2 ★                                    3
Shree Arihant Apartment                               3
Guru Gram Haryana CGHS4.1 ★                           3
Siddhartha Apartment                                  3
Pivotal Riddhi Siddhi                                 3
Adani Aangan Arcade                                   3
Whiteland Blissville                                  3
Signature Global Solera 2                             3
Tulip Purple                                          3
Chintels Paradiso3.9 ★                                3
Essel Tower                                           3
Unitech Sunbreeze                                     3
Raheja Atharva3.6 ★                                   3
Krrish Florence Estate                                3
Sidhartha NCR Greens4.3 ★                             3
Paras Quartier                                        3
Spaze Privy3.9 ★                                      3
Unitech The Residences3.7 ★                           3
Tulip Lemon3.9 ★                                      3
Puri Diplomatic Greens3.9 ★                           3
Conscient Habitat3.6 ★                                3
Today Callidora                                       2
Landmark The Residency                                2
Ramprastha The Atrium3.4 ★                            2
Samaspurkunj                                          2
Mahindra Luminare4.0 ★                                2
Maruti Vihar                                          2
Vipul World Floors                                    2
Unitech Uniworld Gardens 23.4 ★                       2
Apartment                                             2
Lavanya Apartments                                    2
Park Royal Apartment                                  2
Vasant Appartments                                    2
Surendra Avenue 69                                    2
MRG World Ultimus                                     2
BPTP Pedestal                                         2
Mapsko Paradise3.9 ★                                  2
Jammu and Kashmir Bank Employees CGHS3.7 ★            2
Sidhivinayak Apartments                               2
Bhagwati Sadan                                        2
Ambience Caitriona                                    2
Breeze Global Heights                                 2
Silverglades Hightown Residences                      2
Dlf City                                              2
Shapoorji Pallonji Joyville                           2
Milan CGHS 9                                          2
Element One Service                                   2
om appartments                                        2
Ansal Heights3.2 ★                                    2
Suposhaa Smartworld Orchard                           2
Mittal Surya Vihar                                    2
Residency Grand                                       2
M3M Sky Lofts                                         2
Supertech Hilltown                                    2
Bestech Spa Signature                                 2
M3M Latitude                                          2
Vatika INXT Floors                                    2
Palam Vihar Society                                   2
Raheja Vanya                                          2
Housing Board Colony                                  2
HCBS Sports Ville                                     2
Adani Aangan Galleria                                 2
Tulip Orange3.9 ★                                     2
Central Park 2 Bellevue                               2
M3M Urbana                                            2
NBCC Heights3.9 ★                                     2
Supertech Hill Town                                   2
Suncity Avenue 76                                     2
Ashiana Anmol                                         2
Godrej Nature Plus Serenity                           2
The Close South3.9 ★                                  2
Ganga Apartment                                       2
Suncity Heights3.7 ★                                  2
lagoon apartment                                      2
Elan The Presidential                                 2
Oriental Valley CHS                                   2
Aqua Front Towers                                     2
Sahara Grace                                          2
CGHS Airport Apartment                                2
Ansal API Celebrity Suites                            2
Pioneer Urban Presidia                                2
ROF Aalayas3.8 ★                                      2
AWHO Shanti Vihar4.0 ★                                2
Ansal API Esencia3.7 ★                                2
Raheja Atlantis3.8 ★                                  2
Emaar MGF The Enclave                                 2
Ramprastha City                                       2
Vipul Belmonte3.9 ★                                   2
BPTP Amstoria3.8 ★                                    2
The Penthouses at the Hibiscus                        2
M3M Ikonic                                            2
Vatika Emilia Floors3.7 ★                             2
Ardee City3.8 ★                                       2
Tulip Violet                                          2
Tulip Leaf                                            2
Viridian The Plaza 106                                2
Signature Global The Millennia 3                      2
Emaar MGF Palm Studios                                2
Orchid Island4.2 ★                                    2
Green Campus CHS                                      2
DLF The Crest3.6 ★                                    2
Bestech Park View Sanskruti4.1 ★                      2
Professors Enclave CGHS                               2
DLF The Icon3.7 ★                                     2
SS Hibiscus                                           2
BPTP Mansions Park Prime                              2
DLF The Belaire3.9 ★                                  2
Suncity Avenue 1023.9 ★                               2
Puri The Aravallis                                    2
Paras Irene3.7 ★                                      2
BPTP Freedom Park Life4.0 ★                           2
Tulsiani Easy in Homes                                2
The Center Court                                      1
Uphaar Residency 2                                    1
Wings Apartment                                       1
Sidhartha NCR One Phase 24.1 ★                        1
Bestech Park View Ananda                              1

In [76]:
df.rename(columns = {'area':'price_per_sqft'}, inplace = True)

In [77]:
df.sample(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
819,4 BHK Flat in Sector 109 Gurgaon,ATS Tourmaline3.9 ★,2.95 Crore,"₹ 9,365/sq.ft.",Super Built up area 3150(292.64 sq.m.),4 Bedrooms,5 Bathrooms,3+ Balconies,Servant Room,"N/a, Sector 109 Gurgaon, Gurgaon, Haryana",10th of 27 Floors,North-East,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'NeoSquare ...",This 4 bhk apartment is available for sale in ...,[],"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
2983,3 BHK Flat in Sector 95 Gurgaon,Sidhartha NCR One Phase 14.2 ★,90 Lac,"₹ 4,500/sq.ft.",Built Up area: 2000 (185.81 sq.m.),3 Bedrooms,3 Bathrooms,1 Balcony,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",15th of 16 Floors,NaN,1 to 5 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",Residential apartment for sell.Located on 15th...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...","['Power Back-up', 'Lift(s)', 'Swimming Pool', ...","['Management4 out of 5', 'Green Area4 out of 5..."
778,4 BHK Flat in Sector 92 Gurgaon,Sare Homes,1.18 Crore,"₹ 5,207/sq.ft.",Carpet area: 2266 (210.52 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"802, Sector 92 Gurgaon, Gurgaon, Haryana",8th of 21 Floors,North,1 to 5 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",Sare homes is one of gurgaon's most sought aft...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
2231,2 BHK Flat in Palam Vihar,Ansal Plaza,1 Crore,"₹ 10,000/sq.ft.",Built Up area: 1000 (92.9 sq.m.),2 Bedrooms,3 Bathrooms,No Balcony,NaN,"Palam Vihar, Palam Vihar, Gurgaon, Haryana",1st of 1 Floors,NaN,undefined,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Best in class property available at palam viha...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
2459,3 BHK Flat in Sector 63 Gurgaon,Dhoot Time Residency4.0 ★,3 Crore,"₹ 18,271/sq.ft.",Built Up area: 1642 (152.55 sq.m.)Carpet area:...,3 Bedrooms,3 Bathrooms,3+ Balconies,Servant Room,"Sector 63, Sector 63 Gurgaon, Gurgaon, Haryana",14th of 16 Floors,NaN,1 to 5 Year Old,"['Metro Station', 'High end group housing', 'N...",Best in class property available at sector 63 ...,"['3 Wardrobe', '8 Fan', '1 Exhaust Fan', '3 Ge...",NaN,"['Green Area4 out of 5', 'Construction4 out of..."

In [78]:
df['society'].value_counts()

society
SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Smart World Gems                                     32
Emaar MGF Emerald Floors Premier3.8 ★                32
Smart World Orchard                                  32
DLF The Ultima4.0 ★                                  31
Paras Dews                                           31
DLF Regal Gardens3.9 ★                               30
Shree Vardhman Flora3.8 ★                            29
M3M Woodshire4.0 ★                                   29
La Vida by Tata Housing                              28
Signature Global Solera3.7 ★                         28
Godrej Nature Plus                                   27
Emaar Gurgaon Greens4.1 ★                            25
BPTP Terra3.8 ★                                      25
Experion The Heartsong3.9 ★                          24
Eldeco Accolade3.8 ★                                 24
Vatika Gurgaon 213.7 ★                               24
DLF New Town Heights 13.9 ★                          24
Bestech Park View Residency3.9 ★                     23
M3M Heights                                          22
Tata Primanti4.1 ★                                   22
ATS Triumph3.9 ★                                     22
Emaar Palm Gardens4.1 ★                              22
ROF Ananda                                           21
Sare Crescent Parc3.5 ★                              21
Godrej 1014.0 ★                                      20
Experion Windchants3.8 ★                             20
Sare Homes                                           19
Antriksh Heights3.7 ★                                19
Ambience Creacions                                   18
ATS Tourmaline3.9 ★                                  18
Indiabulls Centrum Park3.7 ★                         18
Mapsko Mount Ville4.1 ★                              18
Supertech Araville                                   18
CHD Avenue 713.6 ★                                   18
Sobha City                                           18
M3M Golfestate4.4 ★                                  17
Conscient Heritage Max4.3 ★                          17
GLS Arawali Homes3.8 ★                               17
Godrej Summit3.7 ★                                   17
Pareena Coban Residences                             17
M3M Skywalk                                          17
Bestech Park View Grand Spa4.3 ★                     16
M3M Merlin3.7 ★                                      16
HCBS Sports Ville3.6 ★                               16
Umang Monsoon Breeze                                 15
Emaar MGF The Palm Drive4.1 ★                        15
Ansal Heights 86                                     15
Godrej Oasis3.9 ★                                    15
Umang Winter Hills3.9 ★                              14
Ramsons Kshitij3.7 ★                                 14
DLF The Primus3.9 ★                                  14
Orchid Petals4.1 ★                                   14
The Close North4.0 ★                                 14
Ireo Skyon4.0 ★                                      14
Vatika The Seven Lamps3.8 ★                          14
Ireo Victory Valley4.1 ★                             14
Indiabulls Enigma                                    14
Corona Optus3.9 ★                                    14
Imperia The Esfera                                   14
MVN Athens3.7 ★                                      14
Ireo The Corridors                                   13
Bestech Park View Ananda4.2 ★                        13
Puri Emerald Bay3.7 ★                                13
Central Park Flower Valley                           13
M3M Soulitude                                        11
DLF The Skycourt4.2 ★                                11
Godrej Aria3.8 ★                                     11
TARC Maceo3.8 ★                                      11
SBTL Caladium                                        11
Breez Global Hill View                               11
Adani M2K Oyster Grande3.9 ★                         11
Alpha Corp GurgaonOne 844.0 ★                        11
Raheja Vedaanta3.6 ★                                 11
Puri Diplomatic Greens4.0 ★                          10
Capital Residences 360                               10
ATS Kocoon                                           10
Ramprastha The Edge Towers3.5 ★                      10
Signature Global Synera3.4 ★                         10
DLF New Town Heights 24.0 ★                          10
Breez Global Heights4.2 ★                            10
Emaar MGF Palm Hills4.0 ★                            10
Zara Aavaas                                          10
Pyramid Urban Homes 2                                10
Godrej Air                                           10
Pivotal Devaan                                       10
Parsvnath Green Ville3.9 ★                            9
Bestech Park View Sanskruti4.2 ★                      9
AIPL The Peaceful Homes3.9 ★                          9
Pareena Mi Casa                                       9
Microtek Greenburg3.8 ★                               9
ILD Greens4.1 ★                                       9
Vatika City4.1 ★                                      9
Tulip Ivory3.5 ★                                      8
GLS Avenue 51                                         8
ss                                                    8
Bestech Altura                                        8
AVL 36 Gurgaon3.7 ★                                   8
Orris Aster Court Premier                             8
The Lions CGHS                                        8
Emaar Digihomes                                       8
M3M Capital                                           8
Birla Navya                                           8
Assotech Blith                                        8
Vatika Lifestyle Homes3.8 ★                           8
M3M Skycity                                           8
Signature Andour Heights3.8 ★                         7
Emaar Imperial Gardens3.8 ★                           7
Signature Global Orchard Avenue3.6 ★                  7
Sare Crescent Parc Royal Greens Phase 1               7
Mapsko Casa Bella3.8 ★                                7
Vipul Lavanya3.9 ★                                    7
Ireo The Grand Arch4.0 ★                              7
Signature Global City                                 7
Sare Green ParC Phase 3                               7
Ansal Housing Highland Park                           7
Orris Carnation Residency3.7 ★                        7
Trisara Our Homes 3                                   7
AIPL Zen Residences                                   7
DLF Regency Park 13.6 ★                               6
HSIIDC Sidco Aravali                                  6
Bestech Park View City4.1 ★                           6
Signature Global Park 4                               6
Suncity Vatsal Valley                                 6
Mapsko Royale Ville3.7 ★                              6
Sidhartha NCR One Phase 14.2 ★                        6
Greenopolis                                           6
Hero Homes                                            6
Signature Global City 63A                             6
Signature The Roselia3.6 ★                            6
Pyramid Urban                                         6
Shapoorji Pallonji Joyville Gurugram                  6
Supertech Hues                                        6
Ashiana Mulberry                                      6
BPTP Astaire Gardens3.7 ★                             6
Pioneer Araya3.8 ★                                    6
Bestech Park View Spa Next4.0 ★                       6
Parsvnath Exotica3.7 ★                                6
M3M Sierra 68                                         6
Kiran Residency                                       6
Ireo Uptown4.1 ★                                      5
Silverglades The Melia                                5
Signature Global Grand IVA3.9 ★                       5
Conscient Elevate                                     5
Godrej Habitat                                        5
Essel Towers                                          5
Vatika Sovereign Park                                 5
ATS Marigold                                          5
Adani Brahma Samsara Vilasa                           5
Signature Global City 37D Ph 2                        5
Krisumi Waterfall Residences                          5
Central Park Flower Valley Aqua Front Towers          5
Ashiana Anmol3.5 ★                                    5
Green Court3.7 ★                                      5
Vatika City Homes3.9 ★                                5
DLF Park Place4.1 ★                                   5
Pareena Laxmi Apartments3.6 ★                         5
Satya The Hermitage3.5 ★                              5
Emaar MGF Emerald Estate3.8 ★                         5
Pioneer Park3.8 ★                                     5
Signature Global City 92                              5
Signature Global the Millennia                        5
DLF Regency Park 24.0 ★                               5
Central Park Resorts4.4 ★                             5
Tulip Monsella                                        5
M3M The Marina4.0 ★                                   5
Signature Global City 81                              5
Apna Enclave                                          5
Unitech Vistas                                        4
Global Hill View                                      4
Railway Officers RPF Society                          4
Corona Gracieux                                       4
ILD Grand                                             4
Sare Petioles                                         4
Raheja Navodaya3.6 ★                                  4
Ramprastha Primera                                    4
Unitech Fresco3.8 ★                                   4
Signature The Serenas                                 4
Godrej Frontier3.7 ★                                  4
Prime Habitat                                         4
Tata Gurgaon Gateway3.8 ★                             4
Ramprastha Skyz                                       4
HSIIDC Sidco Shivalik Apartments3.8 ★                 4
DLF New Town Heights3.7 ★                             4
SS The Coralwood3.4 ★                                 4
Lotus Homz4.0 ★                                       4
DLF The Skycourt                                      4
Orris Aster Court                                     4
Godrej Icon                                           4
Emaar Palm Heights                                    4
Krrish Provence Estate                                4
Spaze Privvy The Address3.9 ★                         3
DLF The Arbour                                        3
Sare Green Parc 2                                     3
DLF Express Greens3.9 ★                               3
Ambience Lagoon3.9 ★                                  3
Unitech Heritage City                                 3
The Roselia 2                                         3
Valley View Estate                                    3
Sare Green Parc                                       3
Vatika Independent Floors3.8 ★                        3
Kendriya Vihar4.1 ★                                   3
Piedmont Taksila heights3.6 ★                         3
DLF The Grove                                         3
Tulip Petals3.6 ★                                     3
Shri Ram Apartments                                   3
Unitech Uniworld Gardens3.8 ★                         3
Tulip White3.5 ★                                      3
Smriti Apartment                                      3
Sapphire Eighty Three                                 3
DLF Royalton Tower                                    3
DLF Carlton Estate4.0 ★                               3
Sukhshanti Apartment                                  3
SS Almeria                                            3
DLF Belvedere Towers3.8 ★                             3
Satya Element One                                     3
AIPL Club Residences                                  3
Vatika Xpressions                                     3
Raheja Revanta                                        3
My Home                                               3
Brisk Lumbini Terrace Homes                           3
Deepak Minda                                          3
Maxworth City Residences                              3
Apex Our Homes                                        3
Shri Banke Bihari Society3.8 ★                        3
AFNHB Jalvayu Vihar3.7 ★                              3
Spaze Privy AT43.9 ★                                  3
ATS Kocoon4.2 ★                                       3
Dhoot Time Residency4.0 ★                             3
Sidhartha NCR One                                     3
Raheja Sampada                                        3
Sunischit Apartments                                  3
Bestech Park View City 23.9 ★                         3
Pyramid Elite                                         3
Suncity Platinum Towers                               3
Mahindra Aura4.2 ★                                    3
Shree Arihant Apartment                               3
Guru Gram Haryana CGHS4.1 ★                           3
Siddhartha Apartment                                  3
Pivotal Riddhi Siddhi                                 3
Adani Aangan Arcade                                   3
Whiteland Blissville                                  3
Signature Global Solera 2                             3
Tulip Purple                                          3
Chintels Paradiso3.9 ★                                3
Essel Tower                                           3
Unitech Sunbreeze                                     3
Raheja Atharva3.6 ★                                   3
Krrish Florence Estate                                3
Sidhartha NCR Greens4.3 ★                             3
Paras Quartier                                        3
Spaze Privy3.9 ★                                      3
Unitech The Residences3.7 ★                           3
Tulip Lemon3.9 ★                                      3
Puri Diplomatic Greens3.9 ★                           3
Conscient Habitat3.6 ★                                3
Today Callidora                                       2
Landmark The Residency                                2
Ramprastha The Atrium3.4 ★                            2
Samaspurkunj                                          2
Mahindra Luminare4.0 ★                                2
Maruti Vihar                                          2
Vipul World Floors                                    2
Unitech Uniworld Gardens 23.4 ★                       2
Apartment                                             2
Lavanya Apartments                                    2
Park Royal Apartment                                  2
Vasant Appartments                                    2
Surendra Avenue 69                                    2
MRG World Ultimus                                     2
BPTP Pedestal                                         2
Mapsko Paradise3.9 ★                                  2
Jammu and Kashmir Bank Employees CGHS3.7 ★            2
Sidhivinayak Apartments                               2
Bhagwati Sadan                                        2
Ambience Caitriona                                    2
Breeze Global Heights                                 2
Silverglades Hightown Residences                      2
Dlf City                                              2
Shapoorji Pallonji Joyville                           2
Milan CGHS 9                                          2
Element One Service                                   2
om appartments                                        2
Ansal Heights3.2 ★                                    2
Suposhaa Smartworld Orchard                           2
Mittal Surya Vihar                                    2
Residency Grand                                       2
M3M Sky Lofts                                         2
Supertech Hilltown                                    2
Bestech Spa Signature                                 2
M3M Latitude                                          2
Vatika INXT Floors                                    2
Palam Vihar Society                                   2
Raheja Vanya                                          2
Housing Board Colony                                  2
HCBS Sports Ville                                     2
Adani Aangan Galleria                                 2
Tulip Orange3.9 ★                                     2
Central Park 2 Bellevue                               2
M3M Urbana                                            2
NBCC Heights3.9 ★                                     2
Supertech Hill Town                                   2
Suncity Avenue 76                                     2
Ashiana Anmol                                         2
Godrej Nature Plus Serenity                           2
The Close South3.9 ★                                  2
Ganga Apartment                                       2
Suncity Heights3.7 ★                                  2
lagoon apartment                                      2
Elan The Presidential                                 2
Oriental Valley CHS                                   2
Aqua Front Towers                                     2
Sahara Grace                                          2
CGHS Airport Apartment                                2
Ansal API Celebrity Suites                            2
Pioneer Urban Presidia                                2
ROF Aalayas3.8 ★                                      2
AWHO Shanti Vihar4.0 ★                                2
Ansal API Esencia3.7 ★                                2
Raheja Atlantis3.8 ★                                  2
Emaar MGF The Enclave                                 2
Ramprastha City                                       2
Vipul Belmonte3.9 ★                                   2
BPTP Amstoria3.8 ★                                    2
The Penthouses at the Hibiscus                        2
M3M Ikonic                                            2
Vatika Emilia Floors3.7 ★                             2
Ardee City3.8 ★                                       2
Tulip Violet                                          2
Tulip Leaf                                            2
Viridian The Plaza 106                                2
Signature Global The Millennia 3                      2
Emaar MGF Palm Studios                                2
Orchid Island4.2 ★                                    2
Green Campus CHS                                      2
DLF The Crest3.6 ★                                    2
Bestech Park View Sanskruti4.1 ★                      2
Professors Enclave CGHS                               2
DLF The Icon3.7 ★                                     2
SS Hibiscus                                           2
BPTP Mansions Park Prime                              2
DLF The Belaire3.9 ★                                  2
Suncity Avenue 1023.9 ★                               2
Puri The Aravallis                                    2
Paras Irene3.7 ★                                      2
BPTP Freedom Park Life4.0 ★                           2
Tulsiani Easy in Homes                                2
The Center Court                                      1
Uphaar Residency 2                                    1
Wings Apartment                                       1
Sidhartha NCR One Phase 24.1 ★                        1
Bestech Park View Ananda                              1

In [79]:
# num categories
df['society'].value_counts().shape

(638,)

In [80]:
import re
text = 'HUDA Ashok Vihar Phase 13.9 ★'
re.findall('\d+\.\d+ ★', text)

['13.9 ★']

In [81]:
# remove rating
pattern = re.compile(r'\d+\.\d+ ★')
society = df['society'].apply(lambda x: re.sub(pattern, '', str(x))).str.strip().str.lower()

In [82]:
df['society']  = society

In [83]:
df['price'].str.split().str.get(1).value_counts()

price
Crore    2074
Lac       922
on         11
Name: count, dtype: int64

In [84]:
df.loc[2972]['price']

'Price on Request'

In [85]:
df = df[df['price'] != 'Price on Request']

In [86]:
df['price'].str.split().str.get(1).value_counts()

price
Crore    2074
Lac       922
Name: count, dtype: int64

In [87]:
def treat_price (x) :
  if type(x) == float :
    return x
  if x[1] == 'Lac' :
    return round(float(x[0])/100,2)
  else :
    return round(float(x[0]), 2)

In [88]:
df['price'] = df['price'].str.split().apply(treat_price)

<ipython-input-88-1bcb6b8cd4b7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price'] = df['price'].str.split().apply(treat_price)

In [89]:
df['price']

0        0.45
1        0.50
2        0.40
3        1.47
4        0.70
5        0.41
6        2.00
7        1.80
8        1.10
9        4.75
10       0.96
11       0.29
12       1.35
13       0.95
14       0.70
15       3.95
16       0.90
17       1.05
18        NaN
19       2.20
20       1.01
21       1.85
22       0.86
23       1.85
24       2.85
26       0.42
27       6.15
28       6.25
29       0.42
30       1.35
31       1.60
32       3.25
33       0.45
34       0.85
35       0.75
36       0.82
37       1.80
38       0.30
39       0.78
40       2.00
41       0.74
42       3.20
43       1.30
44       0.25
45       0.95
46       1.99
47       1.05
48       1.83
49       2.25
50       2.80
51       1.60
52       0.83
53       0.83
54       0.80
55       1.25
56       0.23
57       0.30
58       1.55
59       0.79
60       0.50
61       1.01
62       0.95
63       0.99
64       1.10
65       1.90
66       1.00
67       2.50
68       1.10
69       0.29
70       0.55
71       0.65
72       0.50
73       0.32
74       0.93
75       1.20
76       0.30
77       0.56
78       2.70
79       1.00
80       1.45
81       1.25
82       0.46
83       4.50
84       0.64
85       0.28
86       3.87
87       1.38
88       0.43
89       0.28
90       1.10
91       2.00
92       0.90
93       0.90
94       1.75
95       0.93
96       1.80
97       2.10
98       2.00
99       2.00
100      1.29
101      2.85
102      1.10
103      1.65
104      0.24
105      2.10
106      1.90
107      1.10
108      0.32
109      1.70
110      0.32
111      0.45
112      1.20
113      2.10
114      0.45
115      0.42
116      1.55
117      1.30
118      2.75
119      1.25
120      0.42
121      0.40
122      0.34
123      1.25
124      1.50
125      1.30
126      1.60
127      1.50
128      1.50
129      0.90
130      1.50
131      0.80
132      1.25
133      0.26
134      0.42
135      2.50
136      0.90
137      0.42
138      0.50
139      0.90
140      1.30
141      1.70
142      1.25
143      2.91
144      1.15
145      1.20
146      1.50
147      1.30
148      1.75
149      0.55
150      2.50
151      0.43
152      0.80
153      0.45
154      0.70
155      1.95
156      0.45
157      1.70
158      1.10
159      0.50
160      2.80
161      1.45
162      2.20
163      0.90
164      0.40
165      1.35
166      1.85
167      0.25
168      0.88
169      1.15
170      1.60
171      0.85
172      0.75
173      3.35
174      1.50
175      1.65
176      2.00
177      1.75
178      0.90
179      1.25
180      1.00
181      1.08
182      2.15
183      1.00
184      1.65
185      1.79
186      1.80
187      1.45
188      0.22
189      0.36
190      0.25
191      1.15
192      1.65
193      2.90
194      0.60
195      2.40
196      1.25
197      2.15
198      0.29
199      0.38
200      1.50
201      0.39
202      1.60
203      1.70
204      3.25
205      0.60
206      0.27
207      0.95
208      2.65
209      0.36
210      0.55
211      1.32
212      0.59
213      0.45
214      0.90
215      1.40
216      0.95
217      3.00
218      3.67
219      3.85
220      3.29
221      2.33
222      2.79
223      3.40
224      0.72
225      0.40
226      0.56
227      1.10
228      0.71
229      0.78
230      0.40
231      1.85
232      1.10
233      1.41
234      1.45
235      2.20
236      1.10
237      2.05
238      0.60
239      0.80
240      0.41
241      0.90
242      0.54
243      0.82
244      1.00
245      1.85
246      1.42
247      0.55
248      2.29
249      0.97
250      8.25
251      0.30
252      1.65
253      1.99
254      1.00
255      4.25
256      1.25
257      0.95
258      1.05
259      4.10
260      0.50
261      1.65
262      1.60
263      2.10
264      0.90
265      1.10
266      0.92
267      0.70
268      0.99
269      0.71
270      0.88
271      0.91
272      1.25
273      1.05
274      0.66
275      1.83
276      0.53
277      0.80
278      1.71
279      0.65
280      1.30
281      0.82
282      5.70
283      0.88
284      4.00
285      1.93
286      3.45
287      1.70
288      6.15
289      1.40
290      1.48
291      3.25
292      1.49
293      0.30
294      3.49
295      2.15
296      1.40
297      2.00
298      2.30
299      0.54
300      1.25
301      1.05
302      1.25
303      1.00
304      1.70
305      1.30
306      2.12
307      3.90
308      3.00
309      2.20
310      1.35
311      1.67
312      0.90
313      2.37
314      1.98
315      3.70
316      4.67
317      1.29
318      3.65
319      1.70
320      6.15
321      1.40
322      1.48
323      3.49
324      2.15
325      2.00
326      0.54
327      1.25
328      1.05
329      1.25
330      1.00
331      1.70
332      1.30
333      2.12
334      3.00
335      1.35
336      0.90
337      1.98
338      3.70
339      1.29
340      5.60
341      1.25
342      1.27
343      1.36
344      1.00
345      4.25
346      1.80
347      1.25
348      0.27
349      5.50
350      0.85
351      1.07
352      0.95
353      0.87
354      4.10
355      1.27
356      1.47
357      3.45
358      1.18
359      1.55
360      3.39
361      1.54
362      1.42
363      1.30
364      2.25
365      3.50
366      4.80
367      0.78
368      0.88
369      2.60
370      3.40
371      2.90
372      0.70
373      1.50
374      1.28
375      2.51
376      6.50
377      3.63
378      1.85
379      2.45
380      1.38
381      5.90
382      3.00
383      2.01
384      2.10
385      4.25
386      2.55
387      2.00
388      3.25
389      1.60
390      1.50
391      3.75
392      0.95
393      1.40
394      1.56
395      1.35
396      1.40
397      2.26
398      1.20
399      2.08
400      1.75
401      2.99
402      2.10
403      2.87
404      2.35
405      3.00
406      6.00
407      2.35
408      1.90
409      0.72
410      0.65
411      2.34
412      2.57
413      1.71
414      3.79
415      2.05
416      5.20
417      3.20
418      0.69
419      3.75
420      3.65
421      5.49
422      1.05
423      3.35
424      2.40
425      1.71
426      6.30
427      2.20
428      3.25
429     11.25
430      3.30
431      1.51
432      1.38
433      4.60
434      1.40
435      3.50
436      0.99
437      2.65
438      2.40
439      1.65
440      1.25
441      4.00
442      1.80
443      1.75
444      2.35
445      7.15
446      1.64
447      2.80
448      6.75
449      3.50
450      4.60
451      2.25
452      2.20
453      2.85
454      1.76
455      1.00
456      3.60
457      1.78
458      0.98
459      2.82
460      3.21
461      1.90
462      1.19
463      1.35
464      1.80
465      1.35
466      1.70
467      1.60
468      2.65
469      0.55
470      1.40
471      1.26
472      1.70
473      4.10
474      1.01
475      1.45
476      1.60
477      2.99
478      1.90
479      1.75
480      1.30
481      2.95
482      3.40
483      3.32
484      0.95
485      1.55
486      1.54
487      2.45
488      2.60
489      1.83
490      1.09
491      1.87
492      1.05
493      1.77
494      2.20
495      0.60
496      1.80
497      0.64
498      0.75
499      4.95
500      4.25
501      5.31
502      1.40
503      2.80
504      4.10
505      3.40
506      3.05
507      4.25
508      1.16
509      3.55
510      1.80
511      1.75
512      1.20
513      1.52
514      1.55
515      2.40
516      2.35
517      2.28
518      1.10
519      2.30
520      1.35
521      2.45
522      0.90
523      2.80
524      1.40
525      1.36
526      0.98
527      0.56
528      2.20
529      1.20
530      1.33
531      0.87
532      1.09
533      3.00
534      1.75
535      1.75
536      3.80
537      3.50
538      1.78
539      1.08
540      2.03
541      1.12
542      2.00
543      1.04
544      1.25
545      2.05
546      3.19
547      3.85
548      3.20
549      0.89
550      0.49
551      1.65
552      2.35
553      1.40
554      0.97
555      2.35
556      3.32
557      1.25
558      2.80
559      4.70
560      1.30
561      0.62
562      0.80
563      1.73
564      4.45
565      2.30
566      2.20
567      2.12
568      2.25
569      1.90
570      4.40
571      1.75
572      2.80
573      4.63
574      1.32
575      1.16
576      0.27
577      0.28
578      1.79
579      1.55
580      1.55
581      3.35
582      3.50
583      4.80
584      1.50
585      2.78
586      2.25
587      2.55
588      1.25
589      0.85
590      5.25
591      1.30
592      0.75
593      3.65
594      1.65
595      1.25
596      1.42
597      1.27
598      1.65
599      1.24
600      2.70
601      1.98
602      2.50
603      2.29
604      2.98
605      1.35
606      1.37
607      1.55
608      4.25
609      1.28
610      1.95
611      2.35
612      5.00
613      0.99
614      1.95
615      3.30
616      4.75
617      1.50
618      1.54
619      1.27
620      1.17
621      1.80
622      0.80
623      1.76
624      2.22
625      1.24
626      1.12
627      1.90
628      1.35
629      2.22
630      0.90
631      1.75
632      0.67
633      2.95
634      2.04
635      2.24
636      1.31
637      1.70
638      1.19
639      1.75
640      1.12
641      0.92
642      0.90
643      2.30
644      1.58
645      4.25
646      1.68
647      4.55
648      2.85
649      2.35
650      2.30
651      2.26
652      4.78
653      2.00
654      3.75
655      6.16
656      5.30
657      0.75
658      1.25
659      2.00
660      1.30
661      1.75
662      2.00
663      1.78
664      1.15
665      1.65
666      0.21
667      2.75
668      2.72
669      2.40
670      4.10
671      1.12
672      0.65
673      7.50
674     11.00
675      1.26
676      1.80
677      5.90
678      2.90
679      1.59
680      2.21
681      1.48
682      0.98
683      2.04
684      1.50
685      1.49
686      1.20
687      0.86
688      0.90
689      2.00
690      1.85
691      2.65
692      1.50
693      1.75
694      1.32
695      0.80
696      1.20
697      6.50
698      1.17
699      1.15
700      2.48
701      1.35
702      1.15
703      2.95
704      3.40
705      2.80
706      2.15
707      1.76
708      3.45
709      3.30
710      1.75
711      2.78
712      1.42
713      2.40
714      2.28
715      1.90
716      3.25
717      1.60
718      4.45
719      0.82
720      0.50
721      0.52
722      0.28
723      0.29
724      0.97
725      0.80
726      1.45
727      0.55
728      1.10
729      1.40
730      1.42
731      2.95
732      2.60
733      1.10
734      0.75
735      1.30
736      1.49
737      1.19
738      1.15
739      0.99
740      0.78
741      1.15
742      0.80
743      2.20
744      1.55
745      1.55
746      0.90
747      0.90
748      0.85
749      3.00
750      2.12
751      1.05
752      1.65
753      1.50
754      3.40
755      3.50
756      3.15
757      5.25
758      2.78
759      0.72
760      1.55
761      1.50
762      3.05
763      3.83
764      2.25
765      1.40
766      3.75
767      1.51
768      2.70
769      3.35
770      1.50
771      2.20
772      2.55
773      0.45
774      1.18
775      0.85
776      1.49
777      6.50
778      1.18
779      0.80
780      1.42
781      5.00
782      1.72
783      1.95
784      0.75
785      1.72
786      2.50
787      1.70
788      1.14
789      1.35
790      0.27
791      1.40
792      1.25
793      1.18
794      1.10
795      1.21
796      3.45
797      1.95
798      3.65
799      2.30
800      3.40
801      1.14
802      0.96
803      3.05
804      2.35
805      1.05
806      1.02
807      1.08
808      1.75
809      2.45
810      6.00
811      1.68
812      1.26
813      1.82
814      2.58
815      1.75
816      2.60
817      2.90
818      1.40
819      2.95
820      2.25
821      1.40
822      1.26
823      1.70
824      1.43
825      1.30
826      1.32
827      2.00
828      1.43
829      3.46
830      2.25
831      1.70
832      1.80
833      1.35
834      5.40
835      1.55
836      1.60
837      2.09
838      1.75
839      1.38
840      2.25
841      2.40
842      1.72
843      0.88
844      3.15
845      1.72
846      1.47
847      1.10
848      1.32
849      1.30
850      1.35
851      3.00
852      1.60
853      3.00
854      0.90
855      1.75
856      2.00
857      1.80
858      1.60
859      1.40
860      1.80
861      2.70
862      1.55
863      1.15
864      1.49
865      1.91
866      1.05
867      2.14
868      1.02
869      0.56
870      2.50
871      2.00
872      2.20
873      1.65
874      1.60
875      0.85
876      1.40
877      2.09
878      2.51
879      1.69
880      0.98
881      2.00
882      1.95
883      2.10
884      1.55
885      1.98
886      2.05
887      1.40
888      1.40
889      2.36
890      1.65
891      2.65
892      2.63
893      2.25
894      2.55
895      1.15
896      1.45
897      2.60
898      1.55
899      1.20
900      1.55
901      1.65
902      1.05
903      1.29
904      0.56
905      1.26
906      1.91
907      2.20
908      1.98
909      1.11
910      2.25
911      1.05
912      2.60
913      1.04
914      1.25
915      3.40
916      1.25
917      0.41
918      0.75
919      1.70
920      0.87
921      1.25
922      2.35
923      1.73
924      0.97
925      1.35
926      1.32
927      0.71
928      0.78
929      5.50
930      2.30
931      0.43
932      0.98
933      0.80
934      2.65
935      2.35
936      1.29
937      1.83
938      1.39
939      1.12
940      0.65
941      1.50
942      1.90
943      2.35
944      0.60
945      2.00
946      1.57
947      1.44
948      1.26
949      1.05
950      6.44
951      7.56
952      3.80
953      6.75
954      0.65
955      1.75
956      1.54
957      1.40
958      0.97
959      1.35
960      1.75
961      2.20
962      2.45
963      1.50
964      2.40
965      2.45
966      3.00
967      1.65
968      0.88
969      0.88
970      1.28
971      1.34
972      1.32
973      1.13
974      1.38
975      1.16
976      2.33
977      3.05
978      1.25
979      1.25
980      1.05
981      1.25
982      1.10
983      1.30
984      2.28
985      1.20
986      1.22
987      1.10
988      1.15
989      1.20
990      1.40
991      1.10
992      1.00
993      1.52
994      1.80
995      1.60
996      1.55
997      1.30
998      2.25
999      4.79
1000     1.25
1001     1.40
1002     1.38
1003     1.30
1004     1.00
1005     1.00
1006     0.95
1007     1.85
1008     1.65
1009     1.32
1010     1.02
1011     1.88
1012     2.15
1013     2.58
1014     2.25
1015     1.75
1016     0.93
1017     4.75
1018     1.72
1019     6.75
1020     2.45
1021     2.20
1022     5.25
1023     5.00
1024     5.00
1025     2.70
1026     2.65
1027     1.65
1028     2.55
1029     2.55
1030     4.30
1031     1.70
1032     2.40
1033     0.87
1034     1.25
1035     0.99
1036     1.39
1037     2.70
1038     1.75
1039     1.55
1040     1.60
1041     1.40
1042     1.80
1043     1.65
1044     3.55
1045     6.00
1046     1.80
1047     2.50
1048     1.50
1049     1.04
1050     0.53
1051     1.64
1052     2.90
1053     2.36
1054     4.85
1055     1.25
1056     0.92
1057     2.70
1058     0.70
1059     1.25
1060     2.30
1061     2.00
1062     1.08
1063     1.73
1064     1.30
1065     2.85
1066     2.25
1067     2.35
1068     2.80
1069     2.35
1070     2.75
1071     2.36
1072     3.40
1073     0.80
1074     7.00
1075     1.80
1076     2.65
1077     1.05
1078     1.88
1079     1.15
1080     1.33
1081     2.60
1082     2.97
1083     1.80
1084     1.78
1085     1.52
1086     1.55
1087     1.55
1088     0.40
1089     2.40
1090     1.37
1091     2.65
1092     1.16
1093     1.05
1094     1.35
1095     1.35
1096     2.85
1097     0.35
1098     0.88
1099     2.40
1100     3.60
1101     7.50
1102     1.45
1103     2.35
1104     0.94
1105     0.81
1106     3.10
1107     1.39
1108     0.94
1109     0.78
1110     0.85
1111     0.69
1112     2.03
1113     0.80
1114     0.65
1115     1.01
1116     1.27
1117     0.84
1118     1.77
1119     1.68
1120     1.66
1121     1.40
1122     2.29
1123     1.21
1124     0.50
1125     0.71
1126     3.00
1127     1.20
1128     3.25
1129     0.90
1130     1.07
1131     1.20
1132     2.15
1133     1.72
1134     1.36
1135     1.75
1136     1.75
1137     1.38
1138     1.29
1139     1.37
1140     1.32
1141     1.30
1142     1.30
1143     1.50
1144     1.68
1145     1.40
1146     1.50
1147     0.50
1148     0.36
1149     3.10
1150     0.31
1151     0.71
1152     1.15
1153     1.05
1154     2.10
1155     0.28
1156     0.28
1157     0.28
1158     0.28
1159     0.23
1160     0.35
1161     0.51
1162     0.35
1163     0.28
1164     0.36
1165     2.00
1166     2.70
1167     4.94
1168     1.75
1169     1.25
1170     0.92
1171     1.30
1172     0.62
1173     1.92
1174     2.00
1175     2.00
1176     0.75
1177     1.85
1178     0.89
1179     1.25
1180     2.15
1181     3.05
1182     2.65
1183     0.49
1184     1.82
1185     0.50
1186     0.92
1187     1.65
1188     1.10
1189     1.55
1190     1.25
1191     1.60
1192     1.15
1193     1.60
1194     4.00
1195     2.22
1196     3.00
1197     1.00
1198    10.75
1199     9.14
1200     8.35
1201     0.73
1202     0.95
1203     0.48
1204     0.86
1205     0.81
1206     2.90
1207     0.37
1208     0.59
1209     0.60
1210     0.37
1211     0.90
1212     1.66
1213     2.00
1214     1.67
1215     1.10
1216     1.60
1217     1.07
1218     1.76
1219     1.55
1220     5.50
1221     0.27
1222     0.26
1223     1.25
1224     2.10
1225     0.95
1226     0.92
1227     1.25
1228     0.87
1229     1.20
1230     0.80
1231     0.98
1232     1.32
1233     1.35
1234     3.45
1235     2.40
1236     3.45
1237     2.25
1238     1.25
1239     1.43
1240     1.27
1241     1.43
1242     1.25
1243     1.44
1244     1.27
1245     1.10
1246     1.40
1247     0.99
1248     0.86
1249     0.98
1250     0.85
1251     1.79
1252     1.50
1253     1.77
1254     1.50
1255     1.49
1256     1.80
1257     1.06
1258     1.14
1259     0.36
1260     0.34
1261     0.34
1262     0.35
1263     1.05
1264     1.72
1265     1.55
1266     1.50
1267     2.05
1268     2.11
1269     1.18
1270     1.15
1271     1.66
1272     1.68
1273     3.95
1274     2.10
1275     1.64
1276     1.69
1277     6.15
1278     6.10
1279     1.59
1280     1.08
1281     1.09
1282     0.85
1283     3.95
1284     2.50
1285     2.05
1286     2.45
1287     1.50
1288     1.45
1289     1.20
1290     2.40
1291     2.50
1292     1.55
1293     1.76
1294     1.76
1295     1.40
1296     1.10
1297     2.45
1298     3.80
1299     5.75
1300    10.00
1301     6.20
1302     1.75
1303     2.40
1304     1.75
1305     1.40
1306     0.24
1307     0.17
1308     0.31
1309     0.33
1310     0.38
1311     0.21
1312     0.20
1313     1.20
1314     1.26
1315     1.34
1316     2.50
1317     3.70
1318     0.60
1319     2.20
1320     7.00
1321     2.60
1322     5.80
1323     1.80
1324     1.40
1325     2.05
1326     1.17
1327     1.58
1328     1.25
1329     0.37
1330     0.38
1331     0.32
1332     0.32
1333     0.20
1334     0.20
1335     1.22
1336     1.35
1337     0.55
1338     1.12
1339     1.10
1340     0.68
1341     1.19
1342     0.47
1343     2.95
1344     0.98
1345     1.55
1346     1.01
1347     1.51
1348     1.40
1349     1.59
1350     0.56
1351     2.00
1352     1.35
1353     1.90
1354     1.70
1355     1.15
1356     1.10
1357     1.30
1358     4.85
1359     2.20
1360     1.25
1361     1.55
1362     1.90
1363     1.60
1364     3.00
1365     2.20
1366     5.20
1367     2.35
1368     2.77
1369     2.70
1370     2.35
1371     2.79
1372     2.30
1373     2.10
1374     1.35
1375     2.23
1376     2.08
1377     1.30
1378     0.48
1379     2.33
1380     1.75
1381     1.60
1382     1.50
1383     1.90
1384     3.70
1385     3.75
1386     3.40
1387     2.20
1388     0.83
1389     1.45
1390     1.77
1391     0.97
1392     2.35
1393     1.90
1394     0.43
1395     1.62
1396     1.93
1397     1.99
1398     1.23
1399     1.63
1400     1.64
1401     1.25
1402     1.90
1403     1.20
1404     1.63
1405     1.23
1406     0.43
1407     1.07
1408     1.73
1409     1.45
1410     1.87
1411     1.85
1412     1.75
1413     1.23
1414     1.25
1415     5.60
1416     1.45
1417     2.70
1418     0.42
1419     3.45
1420     3.25
1421     0.35
1422     0.33
1423     1.10
1424     1.08
1425     1.40
1426     1.65
1427     1.67
1428     1.45

In [97]:
df.head(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [92]:
df['price_per_sqft'].str.split('/').str.get(1).value_counts()

price_per_sqft
sq.ft.    3004
Name: count, dtype: int64

In [94]:
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹', '').str.replace(',', '').str.strip().astype('float')

In [96]:
df.head(3)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [98]:
df['areaWithType'].value_counts()

areaWithType
Super Built up area 1950(181.16 sq.m.)Carpet area: 1161 sq.ft. (107.86 sq.m.)                                                   17
Super Built up area 1350(125.42 sq.m.)                                                                                          17
Super Built up area 1578(146.6 sq.m.)                                                                                           17
Super Built up area 1650(153.29 sq.m.)Carpet area: 1022.58 sq.ft. (95 sq.m.)                                                    15
Super Built up area 2010(186.74 sq.m.)                                                                                          14
Super Built up area 2150(199.74 sq.m.)                                                                                          12
Super Built up area 1950(181.16 sq.m.)                                                                                          11
Carpet area: 1650 (153.29 sq.m.)                                                                                                11
Super Built up area 1920(178.37 sq.m.)                                                                                          10
Carpet area: 1150 (106.84 sq.m.)                                                                                                10
Super Built up area 1650(153.29 sq.m.)                                                                                          10
Super Built up area 1550(144 sq.m.)                                                                                             10
Carpet area: 1450 (134.71 sq.m.)                                                                                                 9
Carpet area: 1350 (125.42 sq.m.)                                                                                                 9
Carpet area: 489 (45.43 sq.m.)                                                                                                   9
Super Built up area 1640(152.36 sq.m.)                                                                                           9
Super Built up area 1828(169.83 sq.m.)                                                                                           9
Super Built up area 1366(126.91 sq.m.)                                                                                           8
Carpet area: 2400 (222.97 sq.m.)                                                                                                 8
Carpet area: 750 (69.68 sq.m.)                                                                                                   8
Super Built up area 1760(163.51 sq.m.)Built Up area: 1186 sq.ft. (110.18 sq.m.)Carpet area: 1130 sq.ft. (104.98 sq.m.)           8
Carpet area: 1950 (181.16 sq.m.)                                                                                                 8
Carpet area: 900 (83.61 sq.m.)                                                                                                   8
Carpet area: 1800 (167.23 sq.m.)                                                                                                 8
Super Built up area 3400(315.87 sq.m.)                                                                                           7
Carpet area: 1600 (148.64 sq.m.)                                                                                                 7
Carpet area: 1300 (120.77 sq.m.)                                                                                                 7
Super Built up area 1415(131.46 sq.m.)                                                                                           7
Super Built up area 1930(179.3 sq.m.)                                                                                            7
Super Built up area 2408(223.71 sq.m.)                                                                                           7
Super Built up area 2200(204.39 sq.m.)                                                                                           7
Carpet area: 2300 (213.68 sq.m.)                                                                                                 7
Carpet area: 1760 (163.51 sq.m.)                                                                                                 7
Super Built up area 2364(219.62 sq.m.)                                                                                           7
Super Built up area 2350(218.32 sq.m.)                                                                                           7
Carpet area: 1103 (102.47 sq.m.)                                                                                                 7
Super Built up area 2100(195.1 sq.m.)                                                                                            7
Super Built up area 1200(111.48 sq.m.)                                                                                           7
Super Built up area 1538(142.88 sq.m.)                                                                                           7
Super Built up area 3150(292.64 sq.m.)                                                                                           6
Super Built up area 2727(253.35 sq.m.)                                                                                           6
Carpet area: 1423 (132.2 sq.m.)                                                                                                  6
Carpet area: 822 (76.37 sq.m.)                                                                                                   6
Carpet area: 700 (65.03 sq.m.)                                                                                                   6
Carpet area: 1326 (123.19 sq.m.)                                                                                                 6
Super Built up area 2812(261.24 sq.m.)                                                                                           6
Super Built up area 1572(146.04 sq.m.)                                                                                           6
Super Built up area 1750(162.58 sq.m.)                                                                                           6
Super Built up area 2215(205.78 sq.m.)                                                                                           6
Super Built up area 1568(145.67 sq.m.)                                                                                           6
Super Built up area 2290(212.75 sq.m.)                                                                                           6
Super Built up area 2000(185.81 sq.m.)                                                                                           5
Super Built up area 1875(174.19 sq.m.)                                                                                           5
Super Built up area 1975(183.48 sq.m.)                                                                                           5
Super Built up area 2149(199.65 sq.m.)                                                                                           5
Carpet area: 645 (59.92 sq.m.)                                                                                                   5
Carpet area: 1975 (183.48 sq.m.)                                                                                                 5
Super Built up area 1480(137.5 sq.m.)                                                                                            5
Super Built up area 1360(126.35 sq.m.)                                                                                           5
Super Built up area 1000(92.9 sq.m.)                                                                                             5
Super Built up area 1245(115.66 sq.m.)                                                                                           5
Super Built up area 1565(145.39 sq.m.)                                                                                           5
Carpet area: 1050 (97.55 sq.m.)                                                                                                  5
Super Built up area 2025(188.13 sq.m.)                                                                                           5
Super Built up area 1457(135.36 sq.m.)Carpet area: 849 sq.ft. (78.87 sq.m.)                                                      5
Super Built up area 1215(112.88 sq.m.)                                                                                           5
Carpet area: 2000 (185.81 sq.m.)                                                                                                 5
Super Built up area 1960(182.09 sq.m.)                                                                                           5
Built Up area: 700 (65.03 sq.m.)                                                                                                 5
Super Built up area 1700(157.94 sq.m.)                                                                                           5
Super Built up area 1970(183.02 sq.m.)                                                                                           5
Carpet area: 850 (78.97 sq.m.)                                                                                                   5
Super Built up area 1435(133.32 sq.m.)                                                                                           5
Super Built up area 2812(261.24 sq.m.)Built Up area: 2600 sq.ft. (241.55 sq.m.)Carpet area: 2400 sq.ft. (222.97 sq.m.)           5
Carpet area: 450 (41.81 sq.m.)                                                                                                   5
Carpet area: 600 (55.74 sq.m.)                                                                                                   5
Super Built up area 1997(185.53 sq.m.)                                                                                           5
Super Built up area 1850(171.87 sq.m.)                                                                                           5
Carpet area: 1200 (111.48 sq.m.)                                                                                                 5
Super Built up area 2545(236.44 sq.m.)                                                                                           4
Super Built up area 1365(126.81 sq.m.)                                                                                           4
Super Built up area 1942(180.42 sq.m.)                                                                                           4
Carpet area: 800 (74.32 sq.m.)                                                                                                   4
Built Up area: 1350 (125.42 sq.m.)                                                                                               4
Carpet area: 1225 (113.81 sq.m.)                                                                                                 4
Super Built up area 1727(160.44 sq.m.)Carpet area: 1017 sq.ft. (94.48 sq.m.)                                                     4
Built Up area: 2040 (189.52 sq.m.)                                                                                               4
Super Built up area 2191(203.55 sq.m.)                                                                                           4
Super Built up area 1385(128.67 sq.m.)Built Up area: 940 sq.ft. (87.33 sq.m.)Carpet area: 845 sq.ft. (78.5 sq.m.)                4
Super Built up area 600(55.74 sq.m.)                                                                                             4
Super Built up area 1310(121.7 sq.m.)                                                                                            4
Super Built up area 1790(166.3 sq.m.)                                                                                            4
Super Built up area 1900(176.52 sq.m.)Carpet area: 1240.04 sq.ft. (115.2 sq.m.)                                                  4
Carpet area: 1400 (130.06 sq.m.)                                                                                                 4
Super Built up area 2000(185.81 sq.m.)Built Up area: 1900 sq.ft. (176.52 sq.m.)Carpet area: 1800 sq.ft. (167.23 sq.m.)           4
Super Built up area 650(60.39 sq.m.)                                                                                             4
Super Built up area 1261(117.15 sq.m.)                                                                                           4
Super Built up area 2355(218.79 sq.m.)Built Up area: 1535 sq.ft. (142.61 sq.m.)Carpet area: 1403 sq.ft. (130.34 sq.m.)           4
Super Built up area 1081(100.43 sq.m.)                                                                                           4
Super Built up area 1725(160.26 sq.m.)                                                                                           4
Super Built up area 2358(219.07 sq.m.)                                                                                           4
Super Built up area 1900(176.52 sq.m.)                                                                                           4
Super Built up area 1300(120.77 sq.m.)                                                                                           4
Super Built up area 1430(132.85 sq.m.)                                                                                           4
Super Built up area 2400(222.97 sq.m.)                                                                                           4
Carpet area: 1250 (116.13 sq.m.)                                                                                                 4
Super Built up area 1100(102.19 sq.m.)                                                                                           4
Super Built up area 1825(169.55 sq.m.)                                                                                           4
Carpet area: 1549 (143.91 sq.m.)                                                                                                 4
Super Built up area 1103(102.47 sq.m.)                                                                                           4
Carpet area: 481.73 (44.75 sq.m.)                                                                                                4
Super Built up area 1900(176.52 sq.m.)Built Up area: 1600 sq.ft. (148.64 sq.m.)Carpet area: 1240.04 sq.ft. (115.2 sq.m.)         4
Super Built up area 2802(260.31 sq.m.)Built Up area: 2225.56 sq.ft. (206.76 sq.m.)                                               4
Carpet area: 501 (46.54 sq.m.)                                                                                                   4
Carpet area: 1500 (139.35 sq.m.)                                                                                                 4
Super Built up area 1930(179.3 sq.m.)Built Up area: 1929 sq.ft. (179.21 sq.m.)Carpet area: 1928 sq.ft. (179.12 sq.m.)            4
Super Built up area 1457(135.36 sq.m.)                                                                                           4
Super Built up area 2095(194.63 sq.m.)                                                                                           4
Carpet area: 2290 (212.75 sq.m.)                                                                                                 4
Super Built up area 2950(274.06 sq.m.)                                                                                           4
Built Up area: 1103 (102.47 sq.m.)                                                                                               4
Super Built up area 1789(166.2 sq.m.)                                                                                            4
Carpet area: 1340 (124.49 sq.m.)                                                                                                 4
Super Built up area 1780(165.37 sq.m.)                                                                                           4
Carpet area: 366.08 (34.01 sq.m.)                                                                                                3
Carpet area: 690 (64.1 sq.m.)                                                                                                    3
Built Up area: 2400 (222.97 sq.m.)                                                                                               3
Super Built up area 915(85.01 sq.m.)                                                                                             3
Carpet area: 2298 (213.49 sq.m.)                                                                                                 3
Super Built up area 1743(161.93 sq.m.)                                                                                           3
Super Built up area 2000(185.81 sq.m.)Built Up area: 1900 sq.ft. (176.52 sq.m.)Carpet area: 1850 sq.ft. (171.87 sq.m.)           3
Carpet area: 576 (53.51 sq.m.)                                                                                                   3
Super Built up area 767(71.26 sq.m.)                                                                                             3
Super Built up area 1283(119.19 sq.m.)Built Up area: 978.23 sq.ft. (90.88 sq.m.)Carpet area: 734.43 sq.ft. (68.23 sq.m.)         3
Super Built up area 2120(196.95 sq.m.)Built Up area: 1616 sq.ft. (150.13 sq.m.)                                                  3
Super Built up area 2875(267.1 sq.m.)                                                                                            3
Carpet area: 2500 (232.26 sq.m.)                                                                                                 3
Carpet area: 950 (88.26 sq.m.)                                                                                                   3
Super Built up area 1505(139.82 sq.m.)                                                                                           3
Carpet area: 601 (55.83 sq.m.)                                                                                                   3
Carpet area: 1850 (171.87 sq.m.)                                                                                                 3
Super Built up area 2905(269.88 sq.m.)                                                                                           3
Super Built up area 1799(167.13 sq.m.)Carpet area: 1538 sq.ft. (142.88 sq.m.)                                                    3
Built Up area: 1780 (165.37 sq.m.)                                                                                               3
Built Up area: 1310 (121.7 sq.m.)                                                                                                3
Super Built up area 1490(138.43 sq.m.)Carpet area: 863.91 sq.ft. (80.26 sq.m.)                                                   3
Super Built up area 1095(101.73 sq.m.)                                                                                           3
Super Built up area 1755(163.04 sq.m.)                                                                                           3
Built Up area: 1423 (132.2 sq.m.)                                                                                                3
Super Built up area 2047(190.17 sq.m.)                                                                                           3
Super Built up area 1720(159.79 sq.m.)Carpet area: 1095.3 sq.ft. (101.76 sq.m.)                                                  3
Carpet area: 1750 (162.58 sq.m.)                                                                                                 3

In [102]:
df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     944
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64

In [106]:
pattern = re.compile(r'Bedrooms?')
df['bedRoom'] = df['bedRoom'].apply(lambda x : re.sub(pattern, '', str(x))).str.strip().astype('float')

In [107]:
df.columns

Index(['property_name', 'society', 'price', 'price_per_sqft', 'areaWithType',
       'bedRoom', 'bathroom', 'balcony', 'additionalRoom', 'address',
       'floorNum', 'facing', 'agePossession', 'nearbyLocations', 'description',
       'furnishDetails', 'features', 'rating', 'bedroom'],
      dtype='object')

In [108]:
df.drop(columns = ['bedroom'], inplace=True)

In [109]:
df[df['bedRoom'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2849,2 BHK Flat in Sector 107 Gurgaon,signature global solera,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2850,4 BHK Flat in Sector 53 Gurgaon,tulip monsella,NaN,33198.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2851,2 BHK Flat in New Palam Vihar,my home,NaN,4400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2852,2 BHK Flat in Sohna,breez global hill view,NaN,5470.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2922,3 BHK Flat in Sector 99A Gurgaon,pareena coban residences,NaN,5759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2923,1 BHK Flat in Golf Course Ext Road,ikon tower baani city centre,NaN,12437.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2924,2 BHK Flat in Sector 89 Gurgaon,greenopolis,NaN,4820.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2926,4 BHK Flat in C Block Sushant Lok Phase 1,maple heights,NaN,8888.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2927,2 BHK Flat in Sector 99 Gurgaon,assotech blith,NaN,6593.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [110]:
df = df[~df['bedRoom'].isnull()]

In [111]:
df['bedRoom'].isnull().sum()

np.int64(0)

In [113]:
df['bedRoom'] = df['bedRoom'].astype('int')

In [114]:
df.sample(3)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1786,3 BHK Flat in Sector 86 Gurgaon,dlf new town heights,1.26,6113.0,Super Built up area 1930(179.3 sq.m.),3,3 Bathrooms,3 Balconies,"Others,Servant Room","Multiple Options In, Sector 86 Gurgaon, Gurgao...",5th of 22 Floors,West,5 to 10 Year Old,"['City Square', 'Vatika Town Square', 'Bharat ...",Call 95605 zero 9397 for more details and site...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction4.5 out ..."
2347,2 BHK Flat in Sector-5 Sohna,mvn athens sohna gurgaon,0.28,5833.0,Carpet area: 480 (44.59 sq.m.),2,2 Bathrooms,1 Balcony,NaN,"Sector-5 Sohna, Gurgaon, Haryana",2nd of 12 Floors,NaN,1 to 5 Year Old,NaN,"Near to dam dama lake, lush green and 3km away...",NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...",NaN
312,2 BHK Flat in Sector 103 Gurgaon,landmark the residency,0.90,6666.0,Super Built up area 1350(125.42 sq.m.),2,2 Bathrooms,2 Balconies,NaN,"Sector 103 Gurgaon, Gurgaon, Haryana",1st of 14 Floors,South-West,1 to 5 Year Old,"['State bank ATM', 'Dr. Hitesh Dawar', 'Bhardw...",We are the proud owners of this 2 bhk apartmen...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Security / Fire Alarm', 'Intercom Facility',...","['Connectivity4 out of 5', 'Lifestyle4 out of ..."

In [116]:
df['bathroom'].isnull().sum()

np.int64(0)

In [117]:
df['bathroom'].value_counts()

bathroom
2 Bathrooms    1044
3 Bathrooms     989
4 Bathrooms     636
5 Bathrooms     169
1 Bathroom      112
6 Bathrooms      42
7 Bathrooms       5
Name: count, dtype: int64

In [119]:
df['bathroom'] = df['bathroom'].apply(lambda x : re.sub(r'Bathrooms?', '', x)).str.strip().astype('int')

In [121]:
df['balcony'].isnull().sum()

np.int64(0)

In [120]:
df['balcony'].value_counts()

balcony
3 Balconies     974
3+ Balconies    862
2 Balconies     749
1 Balcony       315
No Balcony       97
Name: count, dtype: int64

In [122]:
df['balcony'] = df['balcony'].str.split().str.get(0).str.replace('No', '0')

In [123]:
df.sample(3)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2633,3 BHK Flat in Sector 39 Gurgaon,milan cghs 9,2.00,8333.0,Built Up area: 2400 (222.97 sq.m.),3,3,3+,NaN,"Milan Cghs 9, Sector 39, Gurgaon, Sector 39 Gu...",Ground of 1 Floors,NaN,undefined,"['Rajiv Chowk Mosque', 'Icici bank ATM', 'Hdfc...","3 bhk apartment for sale in sector 39, gurgaon...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
1108,2 BHK Flat in Sector 82 Gurgaon,vatika the seven lamps,0.94,6533.0,Super Built up area 1435(133.32 sq.m.),2,2,3+,Study Room,"Sector 82 Gurgaon, Gurgaon, Haryana",9th of 16 Floors,North,1 to 5 Year Old,"['SS Omnia Mall', 'Golf Course Ext Rd', 'Knowl...","Brokers excuse, 2bhk+ study, 1435sq. Ft., east...","['2 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."
2856,2 BHK Flat in Sector 86 Gurgaon,ansal heights 86,0.74,5441.0,Super Built up area 1360(126.35 sq.m.),2,2,1,Others,"Ansal Heights, Sector 86, Gurgaon, Sector 86 G...",11st of 14 Floors,NaN,Under Construction,"['IRIS Broadway Mall', 'Delhi Jaipur Expresswa...",It's a 2 bedroom flat with an adjoining hall. ...,NaN,"['Intercom Facility', 'Lift(s)', 'Swimming Poo...","['Safety4.5 out of 5', 'Lifestyle5 out of 5', ..."

In [124]:
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     629
Study Room                                       232
Others                                           179
Pooja Room                                       132
Study Room,Servant Room                           81
Store Room                                        76
Pooja Room,Servant Room                           60
Servant Room,Others                               52
Servant Room,Pooja Room                           30
Study Room,Others                                 27
Pooja Room,Study Room,Servant Room,Others         25
Pooja Room,Study Room,Servant Room                24
Servant Room,Store Room                           19
Pooja Room,Study Room                             13
Pooja Room,Study Room,Servant Room,Store Room     12
Servant Room,Study Room                            8
Study Room,Pooja Room                              8
Study Room,Servant Room,Store Room                 7
Pooja Room,Servant Room,Others                     6
Servant Room,Study Room,Pooja Room,Store Room      6
Pooja Room,Store Room                              6
Others,Servant Room                                6
Pooja Room,Others                                  6
Study Room,Servant Room,Others                     5
Pooja Room,Study Room,Store Room                   4
Pooja Room,Store Room,Study Room,Servant Room      4
Study Room,Pooja Room,Store Room                   3
Store Room,Servant Room                            3
Servant Room,Pooja Room,Study Room,Store Room      3
Servant Room,Others,Pooja Room                     2
Study Room,Servant Room,Pooja Room,Store Room      2
Servant Room,Study Room,Store Room                 2
Study Room,Pooja Room,Servant Room                 2
Servant Room,Others,Store Room,Pooja Room          2
Pooja Room,Study Room,Others                       2
Store Room,Pooja Room,Servant Room                 1
Pooja Room,Study Room,Store Room,Servant Room      1
Pooja Room,Servant Room,Study Room,Store Room      1
Servant Room,Pooja Room,Store Room                 1
Study Room,Servant Room,Store Room,Pooja Room      1
Study Room,Servant Room,Pooja Room                 1
Servant Room,Pooja Room,Store Room,Study Room      1
Study Room,Store Room                              1
Store Room,Study Room                              1
Servant Room,Pooja Room,Study Room                 1
Servant Room,Study Room,Pooja Room                 1
Others,Study Room                                  1
Servant Room,Study Room,Others                     1
Store Room,Pooja Room                              1
Name: count, dtype: int64

In [125]:
df['additionalRoom'].isnull().sum()

np.int64(1305)

In [126]:
df['additionalRoom'].fillna('not available', inplace = True)
df['additionalRoom'] = df['additionalRoom'].str.lower()

<ipython-input-126-1cc05d7a1d01>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['additionalRoom'].fillna('not available', inplace = True)

In [127]:
df.sample(3)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1726,3 BHK Flat in Sector 69 Gurgaon,tulip violet,1.46,9252.0,Super Built up area 1578(146.6 sq.m.),3,3,2,pooja room,"Sector 69 Gurgaon, Gurgaon, Haryana",Ground of 14 Floors,North-East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",This beautiful 3 bhk flat in sector 69 gurgaon...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Di...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
1164,2 BHK Flat in Sector 107 Gurgaon,signature global solera,0.36,6581.0,Carpet area: 547 (50.82 sq.m.),2,2,2,not available,"Sector 107 Gurgaon, Gurgaon, Haryana",8th of 14 Floors,South-East,1 to 5 Year Old,"['Gurgaon Dreamz Mall', 'Dwarka Expressway', ""...","Situated in sector 107 gurgaon, signature glob...","['1 Fan', '1 Light', '1 Modular Kitchen', 'No ...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
1752,4 BHK Flat in Sector-33 Sohna,central park flower valley,2.30,12777.0,Carpet area: 1800 (167.23 sq.m.),4,4,3+,"pooja room,servant room","Sector-33 Sohna, Gurgaon, Haryana",5th of 13 Floors,North-East,0 to 1 Year Old,"['Golf Course Extension Rd', 'Rajiv Chowk - So...",9 sports academiesMulti-Cuisine restaurantKids...,"['4 Wardrobe', '4 Fan', '18 Light', '1 Chimney...","['Feng Shui / Vaastu Compliant', 'Security / F...",NaN

In [128]:
df['additionalRoom'].isnull().sum()

np.int64(0)

In [129]:
df['floorNum'].value_counts()

floorNum
2nd   of 4 Floors           74
3rd   of 4 Floors           71
4th   of 4 Floors           62
1st   of 4 Floors           61
12nd   of 14 Floors         49
14th   of 14 Floors         48
Ground of 14 Floors         40
10th   of 14 Floors         35
7th   of 14 Floors          35
8th   of 14 Floors          34
4th   of 14 Floors          28
6th   of 14 Floors          27
2nd   of 2 Floors           26
1st   of 14 Floors          26
3rd   of 3 Floors           26
8th   of 19 Floors          24
5th   of 14 Floors          24
3rd   of 14 Floors          24
1st   of 1 Floors           23
9th   of 9 Floors           23
9th   of 14 Floors          23
11st   of 14 Floors         23
2nd   of 3 Floors           22
5th   of 12 Floors          22
2nd   of 14 Floors          21
8th   of 18 Floors          20
10th   of 19 Floors         18
6th   of 18 Floors          18
7th   of 15 Floors          17
Ground of 1 Floors          17
7th   of 18 Floors          17
10th   of 18 Floors         17
12nd   of 12 Floors         17
9th   of 13 Floors          17
5th   of 15 Floors          16
3rd   of 18 Floors          16
2nd   of 12 Floors          15
6th   of 12 Floors          15
9th   of 15 Floors          15
1st   of 3 Floors           15
6th   of 19 Floors          14
1st   of 2 Floors           13
10th   of 26 Floors         13
3rd   of 13 Floors          13
6th   of 10 Floors          13
5th   of 5 Floors           13
Ground of 4 Floors          13
7th   of 7 Floors           13
10th   of 10 Floors         12
6th   of 15 Floors          12
8th   of 12 Floors          11
16th   of 19 Floors         11
8th   of 8 Floors           11
9th   of 26 Floors          11
15th   of 19 Floors         11
11st   of 18 Floors         11
9th   of 24 Floors          11
17th   of 17 Floors         11
4th   of 10 Floors          11
6th   of 6 Floors           11
4th   of 13 Floors          11
4th   of 12 Floors          10
6th   of 13 Floors          10
3rd   of 5 Floors           10
7th   of 26 Floors          10
2nd   of 19 Floors          10
7th   of 13 Floors          10
1st   of 26 Floors          10
10th   of 12 Floors         10
7th   of 21 Floors          10
12nd   of 18 Floors         10
4th   of 15 Floors          10
3rd   of 9 Floors           10
15th   of 29 Floors          9
3rd   of 12 Floors           9
8th   of 22 Floors           9
18th   of 19 Floors          9
14th   of 19 Floors          9
9th   of 20 Floors           9
13rd   of 14 Floors          9
8th   of 15 Floors           9
7th   of 17 Floors           9
14th   of 15 Floors          9
12nd   of 17 Floors          9
5th   of 18 Floors           9
6th   of 26 Floors           9
7th   of 12 Floors           9
6th   of 16 Floors           9
3rd   of 15 Floors           8
9th   of 18 Floors           8
5th   of 13 Floors           8
3rd   of 19 Floors           8
1st   of 19 Floors           8
12nd   of 24 Floors          8
8th   of 24 Floors           8
9th   of 12 Floors           8
2nd   of 15 Floors           8
12nd   of 26 Floors          8
10th   of 13 Floors          8
8th   of 26 Floors           8
8th   of 13 Floors           8
12nd   of 19 Floors          8
10th   of 17 Floors          8
4th   of 26 Floors           8
2nd   of 5 Floors            8
2nd   of 8 Floors            8
5th   of 9 Floors            8
14th   of 24 Floors          8
2nd   of 10 Floors           7
13rd   of 13 Floors          7
8th   of 21 Floors           7
7th   of 19 Floors           7
12nd   of 15 Floors          7
9th   of 19 Floors           7
5th   of 29 Floors           7
11st   of 24 Floors          7
2nd   of 13 Floors           7
16th   of 16 Floors          7
8th   of 10 Floors           7
12nd   of 13 Floors          7
1st   of 13 Floors           7
4th   of 19 Floors           7
2nd   of 17 Floors           7
11st   of 11 Floors          7
5th   of 20 Floors           7
11st   of 13 Floors          7
10th   of 21 Floors          7
11st   of 26 Floors          7
5th   of 10 Floors           6
Ground of 15 Floors          6
4th   of 17 Floors           6
11st   of 12 Floors          6
7th   of 20 Floors           6
16th   of 18 Floors          6
5th   of 25 Floors           6
5th   of 22 Floors           6
14th   of 27 Floors          6
12nd   of 22 Floors          6
Ground of 16 Floors          6
17th   of 19 Floors          6
1st   of 10 Floors           6
2nd   of 20 Floors           6
10th   of 15 Floors          6
19th   of 19 Floors          6
15th   of 15 Floors          6
10th   of 20 Floors          6
3rd   of 25 Floors           6
11st   of 19 Floors          6
Ground of 3 Floors           6
6th   of 9 Floors            6
1st   of 5 Floors            6
10th   of 29 Floors          6
4th   of 18 Floors           6
9th   of 30 Floors           5
9th   of 11 Floors           5
12nd   of 21 Floors          5
14th   of 16 Floors          5
4th   of 27 Floors           5
Ground of 19 Floors          5
10th   of 24 Floors          5
Ground of 12 Floors          5
15th   of 21 Floors          5
1st   of 15 Floors           5
18th   of 29 Floors          5
10th   of 27 Floors          5
7th   of 8 Floors            5
15th   of 18 Floors          5
8th   of 9 Floors            5
6th   of 11 Floors           5
4th   of 9 Floors            5
11st   of 25 Floors          5
6th   of 20 Floors           5
16th   of 26 Floors          5
8th   of 30 Floors           5
10th   of 25 Floors          5
15th   of 28 Floors          5
12nd   of 29 Floors          5
1st   of 12 Floors           5
11st   of 16 Floors          5
11st   of 29 Floors          5
Ground of 21 Floors          5
7th   of 27 Floors           5
11st   of 30 Floors          5
14th   of 29 Floors          5
5th   of 19 Floors           5
1st   of 7 Floors            5
4th   of 22 Floors           5
6th   of 17 Floors           5
9th   of 22 Floors           5
3rd   of 20 Floors           5
5th   of 8 Floors            5
3rd   of 10 Floors           4
3rd   of 17 Floors           4
14th   of 21 Floors          4
3rd   of 22 Floors           4
7th   of 10 Floors           4
18th   of 32 Floors          4
15th   of 32 Floors          4
19th   of 40 Floors          4
11st   of 20 Floors          4
14th   of 18 Floors          4
23rd   of 26 Floors          4
11st   of 17 Floors          4
7th   of 11 Floors           4
13rd   of 19 Floors          4
17th   of 25 Floors          4
8th   of 16 Floors           4
20th   of 26 Floors          4
19th   of 24 Floors          4
13rd   of 21 Floors          4
Ground of 13 Floors          4
5th   of 24 Floors           4
8th   of 20 Floors           4
25th   of 25 Floors          4
17th   of 26 Floors          4
2nd   of 16 Floors           4
20th   of 20 Floors          4
2nd   of 11 Floors           4
11st   of 15 Floors          4
5th   of 16 Floors           4
2nd   of 9 Floors            4
17th   of 18 Floors          4
6th   of 30 Floors           4
5th   of 23 Floors           4
Ground of 17 Floors          4
3rd   of 11 Floors           4
22nd   of 30 Floors          4
22nd   of 24 Floors          4
14th   of 17 Floors          4
15th   of 23 Floors          4
1st   of 18 Floors           4
7th   of 9 Floors            4
17th   of 24 Floors          4
15th   of 16 Floors          4
14th   of 26 Floors          4
15th   of 25 Floors          4
12nd   of 16 Floors          4
4th   of 8 Floors            4
13rd   of 25 Floors          4
7th   of 24 Floors           4
15th   of 26 Floors          4
9th   of 10 Floors           4
12nd   of 30 Floors          4
6th   of 22 Floors           3
7th   of 23 Floors           3
8th   of 11 Floors           3
16th   of 20 Floors          3
26th   of 30 Floors          3
13rd   of 15 Floors          3
9th   of 16 Floors           3
10th   of 30 Floors          3
6th   of 24 Floors           3
1st   of 25 Floors           3
5th   of 30 Floors           3
12nd   of 27 Floors          3
18th   of 18 Floors          3
15th   of 40 Floors          3
15th   of 22 Floors          3
3rd   of 8 Floors            3
9th   of 40 Floors           3
31st   of 32 Floors          3
1st   of 11 Floors           3
3rd   of 26 Floors           3
6th   of 23 Floors           3
6th   of 29 Floors           3
18th   of 26 Floors          3
23rd   of 23 Floors          3
21st   of 22 Floors          3
4th   of 16 Floors           3
11st   of 27 Floors          3
2nd   of 22 Floors           3
10th   of 23 Floors          3
6th   of 21 Floors           3
14th   of 32 Floors          3
4th   of 21 Floors           3
21st   of 24 Floors          3
30th   of 32 Floors          3
24th   of 24 Floors          3
5th   of 17 Floors           3
19th   of 21 Floors          3
12nd   of 23 Floors          3
5th   of 26 Floors           3
20th   of 28 Floors          3
Ground of 26 Floors          3
15th   of 20 Floors          3
3rd   of 16 Floors           3
17th   of 30 Floors          3
10th   of 16 Floors          3
8th   of 17 Floors           3
2nd   of 26 Floors           3
9th   of 21 Floors           3
19th   of 29 Floors          3
Ground of 18 Floors          3
8th   of 25 Floors           3
15th   of 39 Floors          3
6th   of 8 Floors            3
8th   of 40 Floors           3
18th   of 30 Floors          3
1st   of 35 Floors           3
4th   of 29 Floors           3
17th   of 29 Floors          3
17th   of 20 Floors          3
4th   of 20 Floors           3
10th   of 28 Floors          3
19th   of 30 Floors          3
27th   of 27 Floors          3
1st   of 17 Floors           2
3rd   of 33 Floors           2
18th   of 21 Floors          2
14th   of 28 Floors          2
16th   of 32 Floors          2
16th   of 27 Floors          2
16th   of 24 Floors          2
2nd   of 6 Floors            2
19th   of 27 Floors          2
7th   of 30 Floors           2
13rd   of 30 Floors          2
10th   of 40 Floors          2
13rd   of 20 Floors          2
2nd   of 28 Floors           2
15th   of 31 Floors          2
27th   of 29 Floors          2
24th   of 30 Floors          2
Ground of 23 Floors          2
4th   of 11 Floors           2
9th   of 29 Floors           2
19th   of 20 Floors          2
2nd   of 24 Floors           2
14th   of 20 Floors          2
43   of 47 Floors            2
1st   of 22 Floors           2
16th   of 30 Floors          2
25th   of 29 Floors          2
23rd   of 29 Floors          2
20th   of 23 Floors          2
9th   of 17 Floors           2
11st   of 23 Floors          2
8th   of 23 Floors           2
8th   of 29 Floors           2
3rd   of 32 Floors           2
10th   of 32 Floors          2
2nd   of 7 Floors            2
4th   of 5 Floors            2
Ground of 51 Floors          2
28th   of 30 Floors          2
7th   of 16 Floors           2
17th   of 23 Floors          2
4th   of 7 Floors            2
15th   of 24 Floors          2
13rd   of 40 Floors          2
8th   of 34 Floors           2
25th   of 30 Floors          2
16th   of 21 Floors          2
7th   of 29 Floors           2
8th   of 32 Floors           2
6th   of 31 Floors           2
12nd   of 25 Floors          2
1st   of 24 Floors           2
39th   of 40 Floors          2
9th   of 28 Floors           2
16th   of 34 Floors          2
10th   of 22 Floors          2
7th   of 36 Floors           2
3rd   of 24 Floors           2
2nd   of 18 Floors           2
2nd   of 40 Floors           2
3rd   of 27 Floors           2
2nd   of 21 Floors           2
10th   of 11 Floors          2
2nd   of 25 Floors           2
1st   of 20 Floors           2
1st   of 30 Floors           2
22nd   of 25 Floors          2
1st   of 8 Floors            2
23rd   of 34 Floors          2
18th   of 24 Floors          2
Lower Ground of 4 Floors     2
4th   of 34 Floors           2
20th   of 25 Floors          2
7th   of 22 Floors           2
3rd   of 29 Floors           2
11st   of 21 Floors          2
8th   of 28 Floors           2
21st   of 27 Floors          2
2nd   of 32 Floors           2
15th   of 17 Floors          2
9th   of 27 Floors           2
20th   of 22 Floors          2
1st   of 16 Floors           2
16th   of 36 Floors          2
5th   of 11 Floors           2
40th   of 40 Floors          2
15th   of 45 Floors          2
17th   of 33 Floors          2
31st   of 40 Floors          1
18th   of 20 Floors          1
3rd   of 31 Floors           1
27th   of 30 Floors          1
34th   of 34 Floors          1
5th   of 36 Floors           1
18th   of 35 Floors          1
17th   of 31 Floors          1
21st   of 23 Floors          1
Ground of 5 Floors           1
Ground of 6 Floors           1
Basement of 13 Floors        1
18th   of 22 Floors          1
17th   of 22 Floors          1
24th   of 36 Floors          1
3rd   of 36 Floors           1
5th   of 6 Floors            1
8th   of 35 Floors           1
Lower Ground of 1 Floors     1
5th   of 35 Floors           1
Ground of 2 Floors           1
10th   of 33 Floors          1
13rd   of 47 Floors          1
34th   of 42 Floors          1
17th   of 21 Floors          1
4th   of 39 Floors           1
24th   of 32 Floors          1
20th   of 34 Floors          1
16th   of 22 Floors          1
18th   of 25 Floors          1
23rd   of 28 Floors          1
8th   of 27 Floors           1
28th   of 29 Floors          1
15th   of 27 Floors          1
11st   of 22 Floors          1
Ground of 11 Floors          1
20th   of 47 Floors          1
27th   of 48 Floors          1
6th   of 7 Floors            1
35th   of 51 Floors          1
22nd   of 28 Floors          1
11st   of 36 Floors          1
28th   of 28 Floors          1
Basement of 4 Floors         1
2nd   of 34 Floors           1
4th   of 40 Floors           1
3rd   of 40 Floors           1
20th   of 32 Floors          1
Basement of 28 Floors        1
19th   of 41 Floors          1
19th   of 26 Floors          1
2nd   of 27 Floors           1
14th   of 51 Floors          1
19th   of 39 Floors          1
12nd   of 39 Floors          1
38th   of 40 Floors          1
18th   of 40 Floors          1
6th   of 25 Floors           1
16th   of 25 Floors          1
4th   of 28 Floors           1
7th   of 32 Floors           1
30th   of 40 Floors          1
4th   of 25 Floors           1
19th   of 23 Floors          1
5th   of 27 Floors           1
24th   of 39 Floors          1
20th   of 30 Floors          1
18th   of 51 Floors          1
24th   of 27 Floors          1
19th   of 22 Floors          1
8th   of 31 Floors           1
33rd   of 48 Floors          1
35th   of 35 Floors          1
26th   of 47 Floors          1
Ground of 24 Floors          1
7th   of 25 Floors           1
20th   of 43 Floors          1
21st   of 51 Floors          1
12nd   of 28 Floors          1
10th   of 34 Floors          1
18th   of 23 Floors          1
12nd   of 32 Floors          1
23rd   of 40 Floors          1
5th   of 32 Floors           1
1st   of 9 Floors            1
3rd   of 6 Floors            1
20th   of 40 Floors          1
9th   of 42 Floors           1
10th   of 51 Floors          1
15th   of 30 Floors          1
21st   of 41 Floors          1
32nd   of 32 Floors          1
8th   of 42 Floors           1
26th   of 34 Floors          1
21st   of 29 Floors          1
20th   of 29 Floors          1
13rd   of 18 Floors          1
7th   of 34 Floors           1
10th   of 39 Floors          1
21st   of 26 Floors          1
1st   of 44 Floors           1
7th   of 42 Floors           1
25th   of 36 Floors          1
21st   of 28 Floors          1
14th   of 22 Floors          1
33rd   of 42 Floors          1
2nd   of 36 Floors           1
19th   of 31 Floors          1
16th   of 51 Floors          1
29th   of 31 Floors          1
22nd   of 40 Floors          1
16th   of 41 Floors          1
7th   of 40 Floors           1
12nd   of 40 Floors          1
3rd   of 28 Floors           1
17th   of 28 Floors          1
3rd   of 30 Floors           1
19th   of 32 Floors          1
16th   of 45 Floors          1
22nd   of 23 Floors          1
7th   of 28 Floors           1
21st   of 36 Floors          1
14th   of 41 Floors          1
Ground of 29 Floors          1
22nd   of 26 Floors          1
32nd   of 55 Floors          1
Ground of 40 Floors          1
13rd   of 22 Floors          1
16th   of 35 Floors          1
44   of 47 Floors            1
23rd   of 24 Floors          1
17th   of 47 Floors          1
4th   of 6 Floors            1
30th   of 34 Floors          1
24th   of 31 Floors          1
24th   of 51 Floors          1
29th   of 29 Floors          1
16th   of 31 Floors          1
5th   of 21 Floors           1
12nd   of 34 Floors          1
5th   of 34 Floors           1
9th   of 25 Floors           1
45   of 47 Floors            1
Ground of 25 Floors          1
9th   of 23 Floors           1
33rd   of 33 Floors          1
1st   of 6 Floors            1
20th   of 24 Floors          1
13rd   of 17 Floors          1
29th   of 39 Floors          1
13rd   of 26 Floors          1
14th   of 25 Floors          1
3rd   of 7 Floors            1
Ground of 22 Floors          1
13rd   of 34 Floors          1
23rd   of 36 Floors          1
Name: count, dtype: int64

In [133]:
def handle_floor (x) :
  if type(x) == float :
    return x
  if (x == 'Lower') | (x == 'Ground'):
    return '0'
  if x == 'Basement' :
    return '-1'
  # extract only digit
  pattern = re.compile(r'\d+')
  return re.findall(pattern, x)[0]

In [135]:
df['floorNum'] = df['floorNum'].str.split().str.get(0).apply(handle_floor)

In [136]:
df.sample(3)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1402,4 BHK Flat in Sector 109 Gurgaon,sbtl caladium,1.90,6219.0,Super Built up area 3055(283.82 sq.m.),4,4,3,servant room,"Sector 109 Gurgaon, Gurgaon, Haryana",8,North-East,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Chirag Hospital...",Located in the popular residential address of ...,NaN,"['Water purifier', 'Security / Fire Alarm', 'F...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
247,2 BHK Flat in Sector 37D Gurgaon,signature global the millennia,0.55,9166.0,Super Built up area 850(78.97 sq.m.)Built Up a...,2,2,3,not available,"Sector 37D Gurgaon, Gurgaon, Haryana",3,NaN,0 to 1 Year Old,"['Jharsha Chowk', 'Hero Honda Chowk', 'Rajiv C...","Near to hero honda chowk, nh-8, dwarka express...",NaN,"['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2765,3 BHK Flat in Dwarka Expressway Gurgaon,ansals highland park,1.20,6185.0,Built Up area: 1940 (180.23 sq.m.),3,3,3+,servant room,"Sector 103, Dwarka Expressway, Gurugram, Harya...",4,NaN,Under Construction,"['Dr. Hitesh Dawar', 'Bhardwaj Hospital', 'R K...",This three bedroom for sale comes with an affo...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN

In [137]:
df['facing'].value_counts()

facing
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [138]:
df['facing'].isnull().sum()

np.int64(874)

In [142]:
df.fillna({'facing' : 'NA'}, inplace = True)

In [143]:
df['facing'].isnull().sum()

np.int64(0)

In [144]:
df.insert(loc=4,column='area',value=round((df['price']*10000000)/df['price_per_sqft']))

In [145]:
df.sample(3)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2221,2 BHK Flat in Sector 91 Gurgaon,tarc maceo,0.95,5954.0,1596.0,Super Built up area 1310(121.7 sq.m.),2,2,2,not available,"Sector 91 Gurgaon, Gurgaon, Haryana",10,East,1 to 5 Year Old,"['Manish Gallexie 91', 'Dwarka Expressway', 'R...",I want to sell my 2bhk apartment in anant raj ...,NaN,"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area5 out of 5', 'Construction4 out of..."
77,2 BHK Flat in Sohna,signature global park,0.56,6812.0,822.0,Carpet area: 822 (76.37 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",3,South,0 to 1 Year Old,"['Sector 55-56 metro', 'Global city centre', '...","Property with all amenities dedicated lift, sw...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Amenities5 out of 5'..."
2513,3 BHK Flat in Chakkarpur,essel tower,2.20,12500.0,1760.0,Carpet area: 1760 (163.51 sq.m.),3,4,3+,servant room,"Chakkarpur, Gurgaon, Haryana",3,NA,5 to 10 Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...",It has a garden view and temple in the vicinity,"['1 Water Purifier', '5 Fan', '1 Fridge', '1 E...",NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."

In [147]:
df.insert(loc=1,column='property_type',value='flat')

In [148]:
df.shape

(2997, 20)

In [149]:
df.to_csv('flats_cleaned.csv', index = False)